from __future__ import annotations


def build_info_ui() -> str:
    return r'''<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>信息决策中心 V3.28（兼容 V3.26）</title>
<style>
  body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI","Microsoft YaHei",Arial,sans-serif;margin:0;background:#f5f7fb;color:#1f2937;}
  header{background:#0f172a;color:#fff;padding:14px 22px;display:flex;align-items:center;justify-content:space-between;gap:16px;position:sticky;top:0;z-index:10;box-shadow:0 6px 20px rgba(15,23,42,.18)}
  header h1{font-size:18px;margin:0;font-weight:800}.toplink{color:#bfdbfe;text-decoration:none;margin-left:12px;font-size:13px}
  main{padding:16px 20px;max-width:1420px;margin:0 auto;}
  .panel{background:#fff;border-radius:14px;box-shadow:0 4px 18px rgba(15,23,42,.08);padding:14px;margin-bottom:14px;border:1px solid #e5e7eb;}
  .controls{display:grid;grid-template-columns:repeat(4,minmax(130px,1fr));gap:10px;align-items:end;}
  label{font-size:12px;color:#64748b;display:block;margin-bottom:4px;} input,select,button{border:1px solid #d1d5db;border-radius:10px;padding:9px 10px;font-size:14px;background:#fff;box-sizing:border-box;width:100%;}
  button{cursor:pointer;background:#2563eb;color:#fff;border-color:#2563eb;font-weight:700;}button.secondary{background:#f8fafc;color:#334155;border-color:#cbd5e1;}button.green{background:#16a34a;border-color:#16a34a}button:disabled{opacity:.62;cursor:wait}
  .summary{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:10px;padding:12px}.stat{background:#f8fafc;border:1px solid #e5e7eb;border-radius:8px;padding:10px;min-width:0}.stat .k{font-size:12px;color:#64748b}.stat .v{font-size:18px;font-weight:800;margin-top:4px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.stat .s{font-size:11px;color:#94a3b8;margin-top:3px;}
  .layout{display:block}.tabs{display:flex;flex-wrap:wrap;gap:8px;margin-bottom:10px}.tab{width:auto;background:#f8fafc;color:#334155;border:1px solid #cbd5e1;padding:8px 12px}.tab.active{background:#2563eb;color:#fff;border-color:#2563eb}
  .item{border:1px solid #e5e7eb;border-radius:12px;padding:12px;margin-bottom:10px;background:#fff;}.item h3{font-size:15px;margin:0 0 8px 0;line-height:1.45;}.item h3 a{color:#1e40af;text-decoration:none}.item h3 a:hover{text-decoration:underline}.meta{display:flex;flex-wrap:wrap;gap:6px 10px;font-size:12px;color:#64748b;margin-bottom:8px;}
  .badge{display:inline-flex;border-radius:999px;padding:2px 8px;background:#eef2ff;color:#3730a3;border:1px solid #c7d2fe;font-size:12px;align-items:center}.badge.neg{background:#fef2f2;color:#991b1b;border-color:#fecaca}.badge.pos{background:#f0fdf4;color:#166534;border-color:#bbf7d0}.badge.neu{background:#f8fafc;color:#475569;border-color:#e2e8f0}.badge.warn{background:#fffbeb;color:#92400e;border-color:#fde68a}.badge.macro{background:#eff6ff;color:#1d4ed8;border-color:#bfdbfe}.summary-text{font-size:13px;color:#475569;line-height:1.65;overflow-wrap:anywhere}.detail-text{margin-top:6px;font-size:12px;color:#475569}.detail-text summary{cursor:pointer;color:#1d4ed8;font-weight:700}.detail-text[open] summary{margin-bottom:6px}.evidence{font-size:12px;color:#334155;background:#f8fafc;border-radius:8px;padding:7px 9px;margin-top:8px;line-height:1.55;overflow-wrap:anywhere}
  .side h3{font-size:15px;margin:4px 0 10px}.barline{display:grid;grid-template-columns:90px 1fr 46px;gap:8px;align-items:center;border-bottom:1px dashed #e5e7eb;padding:7px 0;font-size:13px;}.bar{height:10px;background:#eef2f7;border-radius:999px;overflow:hidden;border:1px solid #e2e8f0}.bar i{display:block;height:100%;background:#60a5fa;width:0}.bar i.neg{background:#f87171}.bar i.pos{background:#4ade80}.bar i.warn{background:#facc15}
  .grid2{display:grid;grid-template-columns:1fr 1fr;gap:10px}.global-columns{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:12px;align-items:start}.global-card{background:#f8fafc;border:1px solid #e5e7eb;border-radius:12px;padding:10px;margin-bottom:8px}.global-card h4{font-size:14px;margin:0 0 6px}.global-list{max-height:680px;overflow:auto}.small{font-size:12px;color:#64748b}.log{white-space:pre-wrap;background:#0f172a;color:#e2e8f0;border-radius:10px;padding:10px;max-height:150px;overflow:auto;font-size:12px;}.pager{display:flex;gap:8px;align-items:center;justify-content:center;margin:14px 0}.pager button{width:auto;padding:8px 14px}.pager span{font-size:13px;color:#475569}.empty{padding:26px;text-align:center;color:#64748b;background:#f8fafc;border:1px dashed #cbd5e1;border-radius:12px}.warnbox{background:#fffbeb;border:1px solid #fde68a;color:#92400e;border-radius:12px;padding:10px;line-height:1.55;font-size:13px}.snapshot-box{background:#eff6ff;border:1px solid #bfdbfe;color:#1e40af;border-radius:12px;padding:10px;line-height:1.55;font-size:13px;margin-top:10px}.snapshot-box.loading{background:#fffbeb;border-color:#fde68a;color:#92400e}.snapshot-box.success{background:#f0fdf4;border-color:#bbf7d0;color:#166534}.snapshot-box.error{background:#fef2f2;border-color:#fecaca;color:#991b1b}.formula{background:#f8fafc;border:1px solid #e5e7eb;border-radius:10px;padding:9px;font-size:12px;line-height:1.6;color:#334155;}
  .event-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.event-card{border:1px solid #dbeafe;border-left:4px solid #60a5fa;border-radius:10px;padding:11px;background:#f8fbff;min-width:0}.event-card.high{border-left-color:#ef4444;background:#fff7f7}.event-card h4{margin:0 0 7px;font-size:14px;overflow-wrap:anywhere}.source-links{display:flex;flex-wrap:wrap;gap:8px;margin-top:7px}.source-links a{font-size:12px;color:#1d4ed8}.quality-full{background:#ecfdf5;color:#047857;border-color:#a7f3d0}.quality-excerpt{background:#eff6ff;color:#1d4ed8;border-color:#bfdbfe}.quality-title{background:#fffbeb;color:#92400e;border-color:#fde68a}.quality-rejected{background:#fef2f2;color:#991b1b;border-color:#fecaca}
  .advanced{margin-top:10px;border:1px solid #e2e8f0;border-radius:10px;background:#f8fafc}.advanced>summary{cursor:pointer;padding:10px 12px;font-weight:700;color:#334155}.advanced .controls{padding:0 12px 12px}.overview{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.overview-card{border:1px solid #e2e8f0;border-radius:8px;padding:12px;background:#fff;min-width:0;max-height:260px;overflow:auto}.overview-card h3{font-size:14px;margin:0 0 8px}.overview-card.negative{border-left:4px solid #ef4444}.overview-card.direct{border-left:4px solid #2563eb}.overview-card.quality{border-left:4px solid #16a34a}.overview-card.missing{border-left:4px solid #f59e0b}.compact-evidence{padding:8px 0;border-top:1px solid #edf2f7;overflow-wrap:anywhere}.compact-evidence:first-of-type{border-top:0}.compact-evidence a{color:#1d4ed8;font-weight:700;text-decoration:none}.compact-evidence .small{margin-top:3px;line-height:1.5}.diagnostic-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.diagnostic-grid .panel{margin:0;box-shadow:none;background:#f8fafc}.decision-note{font-size:13px;line-height:1.65;color:#334155;overflow-wrap:anywhere}.section-note{font-size:12px;color:#64748b;margin:0 0 8px;line-height:1.55}.evidence-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px}.evidence-actions button{font-size:12px;padding:8px;background:#eff6ff;color:#1d4ed8;border-color:#bfdbfe}.field-ok{font-size:12px;line-height:1.65;color:#166534;background:#f0fdf4;border:1px solid #bbf7d0;border-radius:8px;padding:8px;overflow-wrap:anywhere}.missing-row{font-size:12px;line-height:1.55;color:#92400e;padding:5px 0;border-bottom:1px dashed #fde68a;overflow-wrap:anywhere}.compact-diagnostics{margin-bottom:14px}.compact-diagnostics .snapshot-box{margin:8px 12px}.compact-diagnostics .summary{margin:0 12px 12px}
  /* V3.28 shares the workbench palette so iframe switches feel like one product. */
  body{background:#07111f;color:#e6f0ff}.panel{background:#101a2c;border-color:#263955;box-shadow:0 16px 40px rgba(0,0,0,.22)}
  label,.small,.section-note,.meta,.stat .k,.stat .s,.pager span{color:#92a6c4}input,select{background:#0d1728;color:#e6f0ff;border-color:#315077}button.secondary,.tab{background:#17243a;color:#cfe1ff;border-color:#315077}.tab.active{background:#2563eb;color:#fff}
  .stat,.item,.overview-card,.global-card,.formula,.advanced,.diagnostic-grid .panel{background:#0d1728;border-color:#263955;color:#e6f0ff}.item h3 a,.compact-evidence a,.source-links a,.detail-text summary{color:#93c5fd}.summary-text,.detail-text,.evidence,.decision-note,.advanced>summary{color:#c9d8ee}.evidence{background:#0b1628}.compact-evidence{border-color:#263955}.barline{border-color:#263955}.bar{background:#1d2d49;border-color:#263955}.empty{background:#0d1728;border-color:#315077;color:#92a6c4}.snapshot-box{background:#0b1d30;border-color:#315077;color:#bfdbfe}.snapshot-box.loading,.warnbox{background:#2a1c08;border-color:#854d0e;color:#fcd34d}.snapshot-box.success,.field-ok{background:#092319;border-color:#166534;color:#bbf7d0}.snapshot-box.error{background:#2a1116;border-color:#7f1d1d;color:#fecaca}.missing-row{color:#fcd34d;border-color:#854d0e}
  @media(max-width:1100px){.controls{grid-template-columns:repeat(2,1fr)}.summary{grid-template-columns:repeat(2,1fr)}.global-columns,.event-grid,.overview,.diagnostic-grid{grid-template-columns:1fr}}
</style>
</head>
<body>
<header><h1>信息决策中心 V3.28 <small>兼容 V3.26 快照</small></h1><div><a class="toplink" href="/auto-trading">返回总控台</a><a class="toplink" href="/screener">股票筛选</a><a class="toplink" href="/ui">行情监控</a></div></header>
<main>
  <section class="panel">
    <div class="controls">
      <div><label>股票代码</label><input id="symbol" value="600519"></div>
      <div><label>股票名称</label><input id="name" value="贵州茅台"></div>
      <div><button id="latestSnapshotBtn" class="secondary info-action" onclick="loadLatestSnapshot()">读取最近快照</button></div>
      <div><button id="refreshInfoBtn" class="green info-action" onclick="refreshAll(true,false)">普通刷新</button></div>
    </div>
    <details class="advanced"><summary>筛选、深度抓取与缓存维护</summary><div class="controls">
      <div><label>抓取/聚合上限</label><input id="limit" type="number" value="180" min="30" max="500"></div>
      <div><label>分页大小</label><input id="pageSize" type="number" value="15" min="5" max="200"></div>
      <div><label>排序</label><select id="sort"><option value="desc">时间倒序</option><option value="asc">时间正序</option></select></div>
      <div><label>信息模块</label><select id="dimensionFilter"><option value="">全部模块</option><option>官方公告/公司披露</option><option>公司消息</option><option>行业消息/政策消息</option><option>宏观经济消息</option><option>市场资金面消息</option><option>国际消息/全球市场</option><option>社会舆情/社区讨论</option></select></div>
      <div><label>事件类别</label><input id="category" placeholder="如 财报业绩"></div>
      <div><label>包含未知日期</label><select id="unknown"><option value="true">包含</option><option value="false">不包含</option></select></div>
      <div><button id="deepRefreshInfoBtn" class="secondary info-action" onclick="refreshAll(false,true)">深度刷新</button></div>
      <div><button id="clearInfoCacheBtn" class="secondary info-action" onclick="clearInfoCache()">清除缓存</button></div>
    </div></details>
    <div id="cacheStateBox" class="snapshot-box">缓存状态：等待加载。空数据时会显示 source_logs 和可执行动作，不再空白。</div>
  </section>

  <section class="panel"><div id="decisionOverview" class="overview"><div class="empty">正在整理当前结论和可追溯证据…</div></div></section>
  <details class="advanced compact-diagnostics"><summary>展开评分、行情字段、快照与证据质量</summary>
    <div id="snapshotBox" class="snapshot-box">详情页优先读取快照，并用最新统一行情纠正旧的字段缺失提示。</div>
    <section class="summary" id="summary"></section>
  </details>

  <div class="layout">
    <section>
      <div class="panel">
        <div class="tabs">
          <button class="tab active" data-tab="items" onclick="switchTab('items')">个股证据</button>
          <button class="tab" data-tab="global" onclick="switchTab('global')">全球行业映射</button>
          <button class="tab" data-tab="calendar" onclick="switchTab('calendar')">未来事件日历</button>
          <button class="tab" data-tab="dedup" onclick="switchTab('dedup')">重复核验</button>
          <button class="tab" data-tab="diagnostics" onclick="switchTab('diagnostics')">数据核验</button>
          <button class="tab" data-tab="framework" onclick="switchTab('framework')">规则说明</button>
        </div>
        <div id="tabItems">
          <div id="items"></div>
          <div class="pager"><button class="secondary" onclick="loadPage(state.page-1)">上一页</button><span id="pagerInfo">--</span><button class="secondary" onclick="loadPage(state.page+1)">下一页</button></div>
        </div>
        <div id="tabGlobal" style="display:none">
          <p class="section-note">兼容原“全球/行业映射”：现已拆成直接信息映射与全球信息背景，避免无关快讯看起来像个股证据。</p>
          <div class="grid2">
            <div class="global-card"><h4>全球/国内要闻模块分布</h4><div id="globalDims"></div></div>
            <div class="global-card"><h4>全球要闻情绪/风险结构</h4><div id="globalSent"></div></div>
          </div>
          <div class="global-columns">
            <div class="global-card"><h4>直接信息映射</h4><p class="section-note">只展示命中公司业务、行业或产业链的证据，并说明是否进入评分。</p><div id="industryMappedItems" class="global-list"></div></div>
            <div class="global-card"><h4>全球信息背景流</h4><p class="section-note">用于理解市场环境；未直接映射的内容不会计入该股票信息分。</p><div id="globalItems" class="global-list"></div></div>
          </div>
        </div>
        <div id="tabCalendar" style="display:none"><div id="calendarBox"></div></div>
        <div id="tabDedup" style="display:none"><div id="dedupBox"></div></div>
        <div id="tabDiagnostics" style="display:none"><div class="diagnostic-grid"><div class="panel"><h3>统计图</h3><div id="charts"></div></div><div class="panel"><h3>评分模型</h3><div id="formula" class="formula">--</div></div><div class="panel"><h3>信息源诊断</h3><div id="sources" class="small">--</div></div><div class="panel"><h3>请求进度</h3><div class="log" id="log">页面日志会显示请求进度。</div></div></div></div>
        <div id="tabFramework" style="display:none"><div id="frameworkBox"></div></div>
      </div>
    </section>
  </div>
</main>
<script>
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let state={page:1,total_pages:1,analysis:null,pageData:null,global:null,tab:'items'};
let requestSeq=0;
let busyToken=0;
const requestControllers={analysis:null,page:null,global:null,snapshot:null,cache:null};
function log(msg){$('log').textContent=new Date().toLocaleTimeString()+' '+msg+'\n'+$('log').textContent;}
function params(){const u=new URLSearchParams(location.search);return {symbol:$('symbol').value.trim(),name:$('name').value.trim(),limit:Math.max(30,Math.min(500,Number($('limit').value)||180)),page_size:Math.max(5,Math.min(200,Number($('pageSize').value)||15)),sort:$('sort').value,include_unknown_date:$('unknown').value,snapshot_id:u.get('snapshot_id')||'',force:u.get('force')==='true'};}
function rememberSnapshot(p,sid){if(!sid)return;const u=new URL(location.href);u.searchParams.set('symbol',p.symbol);u.searchParams.set('name',p.name);u.searchParams.set('limit',String(p.limit));u.searchParams.set('snapshot_id',sid);u.searchParams.delete('force');history.replaceState(null,'',u);}
function stat(k,v,s=''){return `<div class="stat"><div class="k">${esc(k)}</div><div class="v">${esc(v)}</div>${s?`<div class="s">${esc(s)}</div>`:''}</div>`}
function cnInfoValue(v){const raw=String(v??'').trim();const map={macro:'宏观市场',global:'全球市场',company:'公司信息',company_event:'公司事件',industry:'行业信息',market:'市场资金',announcement:'公司公告',news:'新闻资讯',policy:'政策信息',research:'研究信息',general:'一般事件',general_information:'一般信息',sanction_or_blacklist:'制裁或清单限制',export_or_import_restriction:'进出口或市场准入限制',security_review:'国家安全或供应链审查',regulatory_investigation:'监管调查或执法',tariff_change:'关税调整',support_or_subsidy:'产业支持或补贴',monetary_policy:'货币与利率政策',earnings_or_guidance:'业绩或经营指引',operational_disruption:'停产或供应中断',economic_data_release:'宏观经济数据发布',geopolitical_disruption:'地缘冲突或供应中断',official_confirmed:'官方原文确认',multi_source_confirmed:'多源交叉确认',early_warning:'早期预警待确认',single_source:'单一来源待复核',official_primary:'官方原始来源',trusted_media:'高可信媒体',fast_alert:'快速快讯',other:'其他公开来源',reported:'媒体已报道',draft:'拟议或讨论中',rumor:'传闻待核验',official:'官方已发布',effective:'已经生效',scheduled:'已确认待发生',commodity:'商品市场',earnings:'财报业绩',board_meeting:'董事会会议',research_report:'研究报告',holder_change:'股东持股变动',dividend:'分红派息',positive:'正向',negative:'负向',neutral:'中性',mixed:'方向待确认',hit:'缓存命中',stale:'缓存过期',miss:'缓存缺失',error:'读取失败',ok:'正常',ready:'就绪',fresh:'最新数据',refreshed:'已刷新',skipped:'已跳过',disabled:'已禁用',unsupported:'暂不支持',timeout:'请求超时',no_data:'暂无数据',mapped:'已完成行业映射',background_refresh:'后台刷新中',true:'是',false:'否'};return map[raw]||raw}
function cnSourceName(v){const raw=String(v??'').trim();const map={global_news_cache:'全球要闻缓存',global_industry_mapper:'全球行业映射器',info_light:'信息面轻量缓存',info_snapshot:'信息面快照'};return map[raw]||raw||'未知来源'}
function bars(rows,nameKey='name',countKey='count',cls=''){const max=Math.max(1,...(rows||[]).map(x=>Number(x[countKey]||0)));return (rows||[]).map(x=>`<div class="barline"><span>${esc(cnInfoValue(x[nameKey]||x.category||x.source||'--'))}</span><div class="bar"><i class="${cls}" style="width:${Math.max(2,Number(x[countKey]||0)/max*100)}%"></i></div><b>${esc(x[countKey]||0)}</b></div>`).join('')||'<div class="small">暂无统计</div>'}
function sentCls(x){x=String(x||'');return x.includes('正')?'pos':x.includes('负')?'neg':'neu'}
function setPageStatus(message,kind=''){const box=$('cacheStateBox');box.className='snapshot-box'+(kind?' '+kind:'');box.textContent=message;}
function beginAction(buttonId,message){const token=++busyToken;document.querySelectorAll('.info-action').forEach(btn=>{if(!btn.dataset.originalText)btn.dataset.originalText=btn.textContent;btn.disabled=true;btn.textContent=btn.id===buttonId?'处理中…':btn.dataset.originalText;});setPageStatus(message,'loading');return token;}
function endAction(token){if(token!==busyToken)return;document.querySelectorAll('.info-action').forEach(btn=>{btn.disabled=false;btn.textContent=btn.dataset.originalText||btn.textContent;});}
function isAbort(error){return error?.name==='AbortError'}
async function fetchJson(url,options={},channel=''){if(channel&&requestControllers[channel])requestControllers[channel].abort();const controller=new AbortController();if(channel)requestControllers[channel]=controller;try{const response=await fetch(url,{cache:'no-store',...options,signal:controller.signal});if(!response.ok)throw new Error(`请求失败（HTTP ${response.status}）`);return await response.json();}finally{if(channel&&requestControllers[channel]===controller)requestControllers[channel]=null;}}
function evidenceDate(x){return x?.publish_time||x?.published_at_norm||x?.published_at||x?.date||''}
function evidenceAgeDays(x){const ts=Date.parse(evidenceDate(x));return Number.isFinite(ts)?Math.floor((Date.now()-ts)/86400000):99999}
function isNegativeEvidence(x){const label=String(x?.sentiment_label||x?.impact_direction||x?.risk_tag||'');return label.includes('负')||String(x?.impact_direction||'')==='negative'||Number(x?.sentiment_score??50)<=45}
function compactEvidence(x,scope=''){const url=String(x?.url||x?.source_ref||x?.source_url||'').trim();const title=esc(x?.title||'未命名证据');const linked=url&&url!=='#'?`<a href="${esc(url)}" target="_blank" rel="noreferrer">${title}</a>`:title;return `<div class="compact-evidence">${linked}<div class="small">${scope?esc(scope)+' · ':''}${esc(evidenceDate(x)||'日期未知')} · ${esc(cnSourceName(x?.source||x?.source_name||'未知来源'))}${x?.relevance_score!=null?' · 相关性 '+esc(x.relevance_score):''}</div>${x?.transmission_chain?.length?`<div class="small">传导：${esc(x.transmission_chain.join(' → '))}</div>`:''}</div>`}
function openEvidenceTab(tab){switchTab(tab);document.querySelector('.tabs')?.scrollIntoView({behavior:'smooth',block:'start'});}
function renderDecisionOverview(){
  const a=state.analysis||{},n=a.news||{},rows=a.items||n.items||[];
  const mapped=(state.global?.industry_mapped_items||a.industry_mapped_items||[]);
  const direct=mapped.filter(x=>x.included_in_score||x.score_included||x.is_related_to_symbol).sort((x,y)=>Number(y.relevance_score||0)-Number(x.relevance_score||0));
  const negatives=[...rows,...direct].filter(isNegativeEvidence).filter((x,i,all)=>all.findIndex(y=>(y.event_fingerprint||y.url||y.title)===(x.event_fingerprint||x.url||x.title))===i).sort((x,y)=>evidenceAgeDays(x)-evidenceAgeDays(y));
  const currentNeg=negatives.filter(x=>evidenceAgeDays(x)>=0&&evidenceAgeDays(x)<=7&&x.content_quality_status!=='boilerplate_rejected');
  const historicalNeg=negatives.filter(x=>!currentNeg.includes(x));
  const confirmedDirect=direct.filter(x=>x.included_in_score||x.score_included);
  const earlyDirect=direct.filter(x=>!(x.included_in_score||x.score_included));
  const directNegative=confirmedDirect.filter(isNegativeEvidence);
  const cur=a.current_information_summary||{},dq=a.data_quality||n.data_quality||{},cs=a.cache_status||{},finance=a.finance||{},quote=state.global?.quote_snapshot||a.quote_snapshot||{},profile=a.company_profile||{},exposure=state.global?.company_exposure||a.company_exposure||{},coverage=state.global?.industry_coverage||a.industry_coverage||exposure.coverage_catalog||{};
  const conclusion=currentNeg.length||directNegative.length?'存在已确认的近期负面证据，先核对原文和传导范围；自动新增仓位由时效、正文质量、确认级别和风控共同决定。':earlyDirect.length?'已捕获与当前股票直接相关的早期预警，但尚未达到官方或多源确认条件；只提醒核验，不扣重分、不自动阻断。':direct.length?'已有与当前股票直接相关的全球/行业证据，结合公司公告与价格行为观察。':'当前未找到可直接映射到该股票的全球事件；全球快讯只作市场背景。';
  const riskRows=currentNeg.length?currentNeg.slice(0,3):historicalNeg.slice(0,2);
  const riskTitle=currentNeg.length?`7日内负面证据 ${currentNeg.length} 条`:historicalNeg.length?'历史风险证据（不等于突发）':'近期未发现可核验负面证据';
  const sourceProblems=(a.source_logs||n.sources_status||[]).filter(x=>['error','timeout'].includes(String(x.status||''))).map(x=>`${cnSourceName(x.source||x.source_name)}：${x.skipped_reason||cnInfoValue(x.status)}`);
  const missing=[...(quote.metric_missing_reasons||finance.metric_missing_reasons||[]),...(exposure.missing_reasons||profile.missing_reasons||[]),...(a.errors||[]),...sourceProblems].map(String).filter(Boolean).filter((x,i,all)=>all.indexOf(x)===i);
  const cap=Number(quote.total_market_cap||finance.total_market_cap||0);const capText=cap?`${(cap/1e8).toFixed(2)}亿元`:'--';
  const metricText=`动态PE ${quote.pe_ttm??finance.pe_dynamic??'--'}；PB ${quote.pb??finance.pb??'--'}；换手率 ${quote.turnover_rate??finance.turnover??'--'}%；总市值 ${capText}`;
  const confidence=({high:'高',medium:'中',low:'低'})[exposure.classification_confidence]||'待核验';
  const coverageLine=`全行业画像规则 ${coverage.sector_family_count??'--'} 类 / 事件规则 ${coverage.event_rule_count??'--'} 类；当前命中 ${(exposure.matched_sector_family_labels_cn||exposure.matched_sector_families||[]).join('、')||'无'}；置信度 ${confidence}；依据 ${exposure.classification_basis_cn||'待补行业/主营画像'}。`;
  $('decisionOverview').innerHTML=`
    <div class="overview-card quality"><h3>当前结论</h3><div class="decision-note">${esc(conclusion)}</div><div class="small" style="margin-top:8px">信息分 ${esc(a.info_score??'--')}；近期计分 ${esc(cur.current_scoring_count??0)} 条；正文/摘要 ${esc((dq.verified_full_text_count||0)+(dq.structured_excerpt_count||0))} 条。</div><div class="small" style="margin-top:7px"><b>行业覆盖：</b>${esc(coverageLine)}</div></div>
    <div class="overview-card negative"><h3>${esc(riskTitle)}</h3>${riskRows.length?riskRows.map(x=>compactEvidence(x,currentNeg.length?'近期风险':'历史提示')).join(''):'<div class="small">没有满足日期、来源和内容质量要求的负面证据。系统不会用旧质押标题冒充“突发负面”。</div>'}</div>
    <div class="overview-card missing"><h3>缺失数据与行情核对</h3>${missing.length?missing.slice(0,6).map(x=>`<div class="missing-row">${esc(x)}</div>`).join('')+(missing.length>6?`<div class="small">另有 ${missing.length-6} 项，请打开数据核验。</div>`:''):`<div class="field-ok">关键行情字段已由统一快照补齐：${esc(metricText)}。旧筛选快照中的失效缺失提示已清理。</div>`}<div class="small" style="margin-top:7px">行情时间 ${esc(quote.ts||finance.quote_timestamp||'--')}；来源 ${esc(quote.source||finance.quote_source||'--')}；缓存 ${esc(cnInfoValue(cs.status||'--'))}。</div></div>
    <div class="overview-card direct"><h3>证据入口</h3><div class="evidence-actions"><button onclick="openEvidenceTab('items')">个股证据 ${rows.length}</button><button onclick="openEvidenceTab('global')">直接映射 ${direct.length}</button><button onclick="openEvidenceTab('calendar')">未来事件 ${(a.future_event_calendar||{}).count||0}</button><button onclick="openEvidenceTab('diagnostics')">数据核验</button></div><div class="small" style="margin-top:9px">已确认映射 ${confirmedDirect.length} 条；待确认 ${earlyDirect.length} 条。全球背景与个股证据分栏，未直接相关的快讯不计入个股信息分。</div></div>`;
}
function renderSummary(){const a=state.analysis||{};const n=a.news||{};const cur=a.current_information_summary||{};const dq=a.data_quality||n.data_quality||{};const cal=a.future_event_calendar||{};const directRows=(state.global?.industry_mapped_items||a.industry_mapped_items||[]).filter(x=>x.included_in_score||x.score_included||x.is_related_to_symbol);const confirmed=directRows.filter(x=>x.included_in_score||x.score_included).length;const early=directRows.length-confirmed;$('summary').innerHTML=[stat('当前信息分',a.info_score??'--','近期有效证据'),stat('近期计分',cur.current_scoring_count??0,'事件级去重'),stat('正文/摘要',(dq.verified_full_text_count||0)+(dq.structured_excerpt_count||0),'可核验证据'),stat('仅标题',dq.title_only_count??0,'降低权重'),stat('直接全球传导',directRows.length,`确认 ${confirmed} / 待核验 ${early}`),stat('未来事件',cal.count??0,`确认 ${cal.confirmed_count??0} / 推算 ${cal.rule_inferred_count??0}`)].join('');$('formula').innerHTML=`<b>当前计分范围：</b><br>${esc(cur.score_scope||'仅近期、可核验、事件级去重信息参与当前评分；历史信息和未来结果只供观察。')}<br><br><b>正文质量：</b><br>完整正文权重最高，结构化摘要次之，仅标题降低权重，网页壳拒绝进入正文评分。<br><br><b>事件确认：</b><br>快速快讯用于抢先预警；官方原文或两个独立高可信来源确认后，才允许进入全球行业映射分和自动交易风控。<br><br><b>未来事件：</b><br>${esc(cal.scoring_rule||'未来事件只提高观察频率，不直接加减分。')}<br><br><b>信息分公式：</b><br>${esc(a.score_model?.formula||'公司/事件 + 来源可信度 + 财务 + 全球/行业映射 - 传闻风险')}<br><br><b>摘要：</b><br>${esc(a.summary||a.diagnostics?.summary||'--')}`;const cs=a.cache_status||{};const usingSnapshot=!!(a.used_snapshot||a.snapshot_reused||(['hit','stale'].includes(String(cs.status||''))&&String(cs.source||'').includes('info_')));const snapshotLabel=a.mode==='snapshot_miss'?'快照不存在，未自动重抓':usingSnapshot?'使用筛选/最近快照':'使用手动刷新结果';$('snapshotBox').innerHTML=`${snapshotLabel}；快照编号=${esc(a.snapshot_id||'--')}；快照时间=${esc(a.updated_at||a.created_at||'--')}；近期计分=${esc(cur.current_scoring_count??0)}；历史排除=${esc(cur.historical_excluded_count??0)}。`;$('cacheStateBox').className='snapshot-box success';$('cacheStateBox').innerHTML=`缓存状态=${esc(cnInfoValue(cs.status||'--'))}；缓存年龄=${esc(cs.age_seconds??'--')}秒；有效期=${esc(cs.ttl_seconds??'--')}秒；数据源=${esc(cs.source||'--')}；${cs.stale?'当前展示过期缓存，可手动刷新。':'缓存可复用。'}`;renderDecisionOverview();renderCharts();renderSources();renderFramework();renderGlobal();renderCalendar();}
function renderCharts(){const n=(state.analysis||{}).news||{};const st=(state.pageData||{}).stats||{};$('charts').innerHTML=`<div class="small">消息面模块</div>${bars(n.dimension_counts||[])}<div class="small" style="margin-top:10px">事件类别</div>${bars(n.category_counts||st.by_category||[])}<div class="small" style="margin-top:10px">来源占比</div>${bars(n.source_counts||st.by_source||[])}`;}
function renderSources(){const a=state.analysis||{};const n=a.news||{};const status=a.source_logs||n.sources_status||[];$('sources').innerHTML=status.length?status.map(s=>`<div>【${esc(cnSourceName(s.source||s.source_name))}】${esc(s.count??0)}条：${esc(cnInfoValue(s.status||'--'))}${s.elapsed_ms!=null?' · '+esc(s.elapsed_ms)+'毫秒':''}${s.skipped_reason?' · '+esc(cnInfoValue(s.skipped_reason)):''}</div>`).join(''):'暂无诊断；如果个股信息为空，这里会显示最近抓取日志和错误原因。';}
function cnFrameworkKey(v){const raw=String(v??'');const map={dimensions:'信息维度',source_tiers:'信息源分层',official:'官方来源',media:'证券媒体',community:'社区舆情',scoring:'评分规则',dedup:'事件去重',freshness:'时效规则',blocked_sources:'禁用来源',search_engines:'搜索引擎'};return map[raw]||cnInfoValue(raw)}
function formatFrameworkValue(value){if(Array.isArray(value))return value.map(v=>formatFrameworkValue(v)).join('、');if(value&&typeof value==='object')return Object.entries(value).map(([k,v])=>`${esc(cnFrameworkKey(k))}：${formatFrameworkValue(v)}`).join('；');return esc(cnInfoValue(value))}
function renderFramework(){const a=state.analysis||{};const fw=a.message_framework||{};const sp=a.source_policy||{};let html='<div class="warnbox">消息面按宏观经济、行业、公司、市场资金面、国际消息、舆情分层。官方公告优先；社区只作舆情；搜索引擎结果页禁用。</div>';html+='<h3>消息面分析框架</h3>'+Object.entries(fw).map(([k,v])=>`<div class="item"><b>${esc(cnFrameworkKey(k))}</b><div class="small">${formatFrameworkValue(v)}</div></div>`).join('');html+='<h3>信息源分层</h3>'+Object.entries(sp).map(([k,v])=>`<div class="item"><b>${esc(cnFrameworkKey(k))}</b><div class="small">${formatFrameworkValue(v)}</div></div>`).join('');$('frameworkBox').innerHTML=html;}
function cnTime(x){return x?.publish_time||x?.published_at_norm||x?.published_at||x?.date||x?.created_at||'--'}
function cnCrawlTime(x){return x?.crawl_time||x?.fetched_at||x?.created_at||state.analysis?.created_at||'--'}
function cnDirection(v){return ({positive:'正向',negative:'负向',neutral:'中性'}[String(v||'neutral')]||cnInfoValue(v||'neutral'))}
function cnIncluded(x){return (x.included_in_score||x.score_included)?'已确认并纳入个股评分':x.is_related_to_symbol?'直接相关但待确认，不计分':'仅作市场背景'}
function mappedCard(x){const url=String(x.url||x.source_url||x.source_ref||'').trim();const duplicateCount=Math.max(Number(x.event_cluster_size||0),Number(x.duplicate_count||1));const chain=(x.mapped_chain||x.transmission_chain||[]).join(' → ');return `<div class="global-card"><h4>${url&&url!=='#'?`<a href="${esc(url)}" target="_blank" rel="noreferrer">${esc(x.title||'--')}</a>`:esc(x.title||'--')}</h4><div class="meta"><span class="badge ${x.confirmation_level==='official_confirmed'||x.confirmation_level==='multi_source_confirmed'?'quality-full':'quality-title'}">${esc(x.confirmation_level_cn||'待复核')}</span><span class="badge neu">${esc(x.event_stage_cn||'阶段未知')}</span><span class="badge ${x.impact_direction==='negative'?'neg':x.impact_direction==='positive'?'pos':'neu'}">${esc(cnDirection(x.impact_direction))}</span></div><div class="small">${esc(x.source_tier_cn||'公开来源')}：${esc(x.source||x.source_name||'--')}；发布时间：${esc(cnTime(x))}；抓取时间：${esc(cnCrawlTime(x))}${duplicateCount>1?`；已合并 ${duplicateCount} 条同事件信息`:''}</div><div class="small">行业：${esc((x.mapped_industries||[]).join('、')||'--')}；概念：${esc((x.mapped_concepts||[]).join('、')||'--')}；相关个股：${esc((x.mapped_symbols||[]).join('、')||'--')}</div><div class="small">事件：${esc(x.event_type_cn||cnInfoValue(x.category||x.event_type||'general'))}；相关性：${esc(x.relevance_score??'--')}；${esc(cnIncluded(x))}</div><div class="small"><b>决策范围：</b>${esc(x.decision_scope_cn||'尚无可验证传导对象')}；<b>评分用途：</b>${esc(x.decision_use_cn||'仅展示，不进入评分')}</div>${chain?`<div class="small"><b>传导路径：</b>${esc(chain)}</div>`:''}<div class="summary-text"><b>交易用途：</b>${esc(x.mapped_trade_gate_cn||x.trade_gate_cn||'仅观察，不触发交易')}</div>${x.event_direction_reason_cn?`<div class="summary-text"><b>方向依据：</b>${esc(x.event_direction_reason_cn)}</div>`:''}<div class="summary-text">影响原因：${esc(x.impact_reason||x.explanation||'--')}</div>${url&&url!=='#'?`<div class="source-links"><a href="${esc(url)}" target="_blank" rel="noreferrer">核对原始信息</a></div>`:'<div class="small">未提供可追溯原始链接，本条仅供观察且不得触发自动买入。</div>'}</div>`}
function renderLongText(value,maxLength=360){const text=String(value||'').trim();if(!text)return '';if(text.length<=maxLength)return `<div class="summary-text">${esc(text)}</div>`;return `<div class="summary-text">${esc(text.slice(0,maxLength))}…</div><details class="detail-text"><summary>展开完整摘要</summary><div class="summary-text">${esc(text)}</div></details>`}
function qualityMeta(x){const raw=String(x.content_quality_status||'title_only');const map={full_text:['正文已核验','quality-full'],structured_excerpt:['结构化摘要','quality-excerpt'],title_only:['仅标题证据','quality-title'],boilerplate_rejected:['网页壳已拒绝','quality-rejected']};return map[raw]||[cnInfoValue(raw),'quality-title']}
function renderItem(x){const sent=x.sentiment_label||((Number(x.sentiment_score||50)>=58)?'正面':(Number(x.sentiment_score||50)<=45?'负面':'中性'));const url=String(x.url||x.source_ref||'').trim();const attachment=String(x.attachment_url||'').trim();const title=esc(x.title||'--');const titleHtml=url&&url!=='#'?`<a href="${esc(url)}" target="_blank" rel="noreferrer">${title}</a>`:`<span>${title}</span>`;const evidence=(x.evidence||[]).map(esc).join('；');const quality=qualityMeta(x);const merged=Math.max(Number(x.event_cluster_size||0),Number(x.duplicate_count||1));const eventBadges=x.confirmation_level?`<span class="badge ${x.confirmation_level==='official_confirmed'||x.confirmation_level==='multi_source_confirmed'?'quality-full':'quality-title'}">${esc(x.confirmation_level_cn||cnInfoValue(x.confirmation_level))}</span><span class="badge neu">${esc(x.event_stage_cn||cnInfoValue(x.event_stage))}</span>`:'';const links=`<div class="source-links">${url&&url!=='#'?`<a href="${esc(url)}" target="_blank" rel="noreferrer">打开信息页面</a>`:'<span class="small">未提供原文链接</span>'}${attachment?`<a href="${esc(attachment)}" target="_blank" rel="noreferrer">打开公告PDF</a>`:''}</div>`;return `<article class="item"><h3>${titleHtml}</h3><div class="meta"><span>发布：${esc(cnTime(x))} / 事件：${esc(x.event_time||'--')} / 抓取：${esc(cnCrawlTime(x))}</span><span>来源：${esc(cnSourceName(x.source))}</span><span class="badge ${quality[1]}">${esc(quality[0])}</span>${eventBadges}<span class="badge macro">${esc(cnInfoValue(x.message_dimension||'公司信息'))}</span><span class="badge ${sentCls(sent)}">${esc(cnInfoValue(sent))}</span><span class="badge neu">${esc(cnInfoValue(x.category||'其他'))}</span><span class="badge warn">可信 ${esc(x.credibility_score??'--')} / 影响 ${esc(x.impact_score??'--')} / 传闻风险 ${esc(x.fake_risk_score??'--')}</span>${merged>1?`<span class="badge neu">已合并 ${merged} 条同事件信息</span>`:''}</div>${renderLongText(x.summary)}${!x.summary&&x.content_missing_reason?`<div class="warnbox">${esc(x.content_missing_reason)}</div>`:''}${links}${x.target_relation?`<div class="evidence"><b>当前标的关系：</b>${esc(x.target_relation)}；${esc(x.relation_note||'')}</div>`:''}${evidence?`<div class="evidence"><b>证据：</b>${evidence}</div>`:''}${merged>1?`<div class="small">合并来源：${esc((x.duplicate_sources||[]).join('、')||'--')}</div>`:''}<div class="small">事件类型：${esc(x.event_type_cn||cnInfoValue(x.event_type||'general'))}；阶段：${esc(x.event_stage_cn||cnInfoValue(x.event_stage||'--'))}；确认：${esc(x.confirmation_level_cn||cnInfoValue(x.confirmation_level||'--'))}；决策范围：${esc(x.decision_scope_cn||'尚无可验证传导对象')}；评分用途：${esc(x.decision_use_cn||'仅展示，不进入评分')}；${esc(x.trade_gate_cn||'仅观察，不触发交易')}；去重键：${esc(x.event_fingerprint||x.event_key||x.duplicate_group||'--')}</div></article>`}
function renderCalendar(){
  const cal=state.analysis?.future_event_calendar||{},rows=cal.events||[];
  const intro=`<div class="warnbox"><b>未来事件不直接计分。</b> ${esc(cal.scoring_rule||'只用于提高观察频率。')}<br>${esc(cal.truth_rule||'规则推算日期需再次核对官方日历。')}</div>`;
  const cards=rows.map(x=>{const channels=(x.transmission_channels||[]).join(' → ');return `<article class="event-card ${x.attention_level==='高'?'high':''}"><h4>${esc(x.scheduled_at||'--')} · ${esc(x.title||x.event_type_cn||'未来事项')}</h4><div class="meta"><span class="badge ${x.confirmation_status==='公开来源已确认'?'quality-full':'quality-title'}">${esc(x.confirmation_status||'待核验')}</span><span class="badge ${x.attention_level==='高'?'neg':'neu'}">关注级别 ${esc(x.attention_level||'低')}</span><span>${esc(x.days_until??'--')} 天后</span></div><div class="small">${esc(x.event_scope||'影响范围待核验')}；影响窗口：${esc(x.impact_window||'--')}；方向：${esc(x.impact_direction||'结果待确认')}</div>${channels?`<div class="summary-text"><b>可能传导：</b>${esc(channels)}。只描述传导路径，不预测结果方向。</div>`:''}<div class="summary-text"><b>监控动作：</b>${esc(x.monitoring_action||'加入观察清单')}</div><div class="small warn"><b>交易门控：</b>${esc(x.risk_gate||x.auto_trade_rule||'不依据未来事件自动买入')}</div>${x.source_ref?`<div class="source-links"><a href="${esc(x.source_ref)}" target="_blank" rel="noreferrer">核对公开来源</a></div>`:`<div class="small">${esc(x.confirmation_note||'无公开链接，必须再次核对官方日历')}</div>`}</article>`}).join('');
  $('calendarBox').innerHTML=intro+(rows.length?`<div class="event-grid" style="margin-top:10px">${cards}</div>`:'<div class="empty" style="margin-top:10px">未来观察范围内暂无带明确日期的公开事项；系统不会因此伪造会议或财报日期。</div>');
}
function renderItems(){const d=state.pageData||{};const original=d.data||[];let data=original;const dim=$('dimensionFilter').value;if(dim)data=data.filter(x=>(x.message_dimension||'')===dim);const rawItems=state.analysis?.items||state.analysis?.news?.items||[];const rawTotal=rawItems.length||d.total||original.length;const unknown=rawItems.filter(x=>!(x.publish_time||x.published_at_norm||x.published_at||x.date)).length;const mappedList=(state.analysis?.industry_mapped_items||[]).filter(x=>x.included_in_score||x.score_included);const mappedRelated=mappedList.length;const snapTime=state.analysis?.created_at||'--';let empty=mappedRelated?`<div class="empty">暂无个股新闻；以下展示 ${mappedRelated} 条行业/题材映射证据作为背景，不冒充个股新闻。快照时间：${esc(snapTime)}</div>`+mappedList.slice(0,12).map(mappedCard).join(''):`<div class="empty">暂无信息：当前没有个股条目；抓取日志和错误原因仍保留在下方，可读取最近快照、普通刷新或深度刷新。快照时间：${esc(snapTime)}</div>`;if(!data.length&&original.length)empty='<div class="empty">当前过滤条件导致 0 条。<button class="secondary" onclick="clearInfoFilters()">清空过滤条件</button></div>';$('items').innerHTML=data.length?data.map(renderItem).join(''):empty;$('pagerInfo').textContent=`第 ${state.page} / ${state.total_pages||1} 页；总数 ${d.total??0}；原始 ${rawTotal}；过滤后 ${data.length}；行业映射 ${mappedRelated}；未知日期 ${unknown}；模块=${$('dimensionFilter').value||'全部'}；事件=${$('category').value||'全部'}；包含未知日期=${cnInfoValue($('unknown').value)}`;}
function renderDedup(){const st=(state.pageData||{}).stats||{};const duplicates=st.duplicate_groups||[];$('dedupBox').innerHTML=`<div class="warnbox">重复组用于检查“同一事件多源转载是否重复计分”。系统按 event_key/duplicate_group 合并，只保留最高可信版本进入主评分。</div>${duplicates.length?duplicates.map(x=>`<div class="item"><b>${esc(x.title||'--')}</b><div class="small">重复 ${esc(x.c)} 条；去重键=${esc(x.duplicate_group||'')}</div></div>`).join(''):'<div class="empty">暂无重复组，或当前库已按事件合并。</div>'}`;}
function renderGlobal(){const g=state.global||{};const items=g.items||state.analysis?.global_items||[];const mapped=g.industry_mapped_items||state.analysis?.industry_mapped_items||[];const direct=mapped.filter(x=>x.included_in_score||x.score_included||x.is_related_to_symbol);$('globalDims').innerHTML=`<div class="small">国内 ${g.domestic_count||0} / 全球 ${g.global_count||items.length||0} / 商品 ${g.commodity_count||0} / 当前股票直接相关 ${direct.length}；更新时间 ${esc(g.updated_at||state.analysis?.created_at||'--')}</div>`+bars(g.dimension_counts||g.category_counts||[]);$('globalSent').innerHTML=bars(g.market_category_counts||g.category_counts||[])+'<div class="small" style="margin-top:8px">情绪结构</div>'+bars([{name:'正向',count:g.positive_count||0},{name:'负向',count:g.negative_count||0},{name:'中性',count:g.neutral_count||0}]);$('industryMappedItems').innerHTML=direct.length?direct.slice(0,80).map(mappedCard).join(''):'<div class="empty">暂无与当前股票直接相关的全球/行业证据。无关快讯仍保留在右侧背景流，但不会计入个股信息分。</div>';$('globalItems').innerHTML=items.length?items.slice(0,180).map(renderItem).join(''):'<div class="empty">暂无全球要闻；请到“数据核验”查看来源状态或执行普通/深度刷新。</div>';}
async function loadPage(page=1){const p=params();page=Math.max(1,page);$('pagerInfo').textContent='正在加载分页…';let url=`/api/info/items/${encodeURIComponent(p.symbol)}?page=${page}&page_size=${p.page_size}&sort=${p.sort}&include_unknown_date=${p.include_unknown_date}`;if($('category').value.trim())url+='&category='+encodeURIComponent($('category').value.trim());const js=await fetchJson(url,{},'page');if(js.ok===false)throw new Error(js.message||js.error||'信息分页读取失败');state.pageData=js.data||{};state.total_pages=state.pageData.total_pages||1;if(page>state.total_pages&&state.total_pages>0)return loadPage(1);state.page=page;renderItems();renderCharts();renderDedup();return state.pageData;}
function clearInfoFilters(){$('dimensionFilter').value='';$('category').value='';$('unknown').value='true';state.page=1;loadPage(1).catch(error=>{if(!isAbort(error)){log('过滤刷新失败：'+error.message);$('pagerInfo').textContent='分页读取失败，请重试';}})}
async function loadGlobal(force=false){const p=params();if(force||!state.global)log('读取全球/国内/商品要闻并映射当前股票');const js=await fetchJson(`/api/news/global?limit=${Math.min(200,p.limit)}&force=${force}&symbol=${encodeURIComponent(p.symbol)}&name=${encodeURIComponent(p.name)}`,{},'global');if(js.ok===false)throw new Error(js.message||js.error||'全球要闻读取失败');state.global=js.data||{};if(state.analysis&&Array.isArray(state.global.industry_mapped_items)){state.analysis.industry_mapped_items=state.global.industry_mapped_items;state.analysis.global_items=state.global.items||[];state.analysis.company_exposure=state.global.company_exposure||state.analysis.company_exposure||{};state.analysis.industry_coverage=state.global.industry_coverage||state.analysis.industry_coverage||{};state.analysis.quote_snapshot=state.global.quote_snapshot||state.analysis.quote_snapshot||{};state.analysis.global_news_used={...(state.analysis.global_news_used||{}),related_count:state.global.related_count||0,updated_at:state.global.updated_at};}renderGlobal();renderDecisionOverview();return state.global;}
async function refreshAll(force=false,deep=false){const seq=++requestSeq;const p=params();const buttonId=deep?'deepRefreshInfoBtn':'refreshInfoBtn';const token=beginAction(buttonId,`${deep?'深度刷新':force?'普通刷新':'读取快照/缓存'}中，请稍候…`);const refreshSnapshot=force||deep;if(refreshSnapshot)state.global=null;log((deep?'深度刷新':force?'普通刷新':'读取快照/缓存')+`：${p.name||p.symbol}，上限 ${p.limit} 条`);const sid=refreshSnapshot?'':p.snapshot_id;const url=`/api/info/analyze/${encodeURIComponent(p.symbol)}?name=${encodeURIComponent(p.name)}&limit=${p.limit}&force=${force}&deep_refresh=${deep}&snapshot_id=${encodeURIComponent(sid)}`;try{const js=await fetchJson(url,{},'analysis');if(seq!==requestSeq)return;if(!js.ok)throw new Error(js.message||js.error||'信息分析失败');state.analysis=js.data||{};rememberSnapshot(p,state.analysis.snapshot_id||js.snapshot_id);renderSummary();const results=await Promise.allSettled([loadPage(1),loadGlobal(force||deep)]);if(seq!==requestSeq)return;if(results[0].status==='rejected'&&!isAbort(results[0].reason)){const fallbackItems=state.analysis.items||state.analysis.news?.items||[];state.pageData={data:fallbackItems,total:fallbackItems.length,total_pages:1,stats:state.analysis.stats||{}};state.page=1;state.total_pages=1;renderItems();renderCharts();renderDedup();log('分页接口暂不可用，已展示分析快照内的数据');}if(results[1].status==='rejected'&&!isAbort(results[1].reason))log('全球要闻暂未更新：'+results[1].reason.message);renderSummary();log(`分析完成：信息面分=${state.analysis.info_score??'--'}，新闻=${state.analysis.news?.count??0}条，政策线索=${state.analysis.policy?.policy_clue_count??0}，${state.analysis.snapshot_reused?'复用快照':'已重新抓取/刷新'}`);}catch(error){if(!isAbort(error)&&seq===requestSeq){setPageStatus('信息分析失败：'+error.message,'error');log('信息分析失败：'+error.message);}}finally{endAction(token);}}
async function loadLatestSnapshot(){const p=params();const token=beginAction('latestSnapshotBtn','正在读取最近信息快照…');try{const js=await fetchJson(`/api/cache/info/latest/${encodeURIComponent(p.symbol)}`,{},'snapshot');if(js.ok&&js.data){state.analysis=js.data;rememberSnapshot(p,js.snapshot_id||state.analysis.snapshot_id);const fallbackItems=state.analysis.items||state.analysis.news?.items||[];state.pageData={data:fallbackItems,total:fallbackItems.length,total_pages:1,stats:state.analysis.stats||{}};state.page=1;state.total_pages=1;renderSummary();renderItems();renderCharts();renderDedup();const results=await Promise.allSettled([loadPage(1),loadGlobal(false)]);if(results[0].status==='rejected'&&!isAbort(results[0].reason))log('分页接口暂不可用，继续展示快照内的数据');if(results[1].status==='rejected'&&!isAbort(results[1].reason))log('全球要闻暂未更新：'+results[1].reason.message);renderSummary();log('已读取最近信息快照 '+(js.snapshot_id||state.analysis.snapshot_id||''));}else{log('暂无最近快照，自动执行普通刷新');await refreshAll(true,false);}}catch(error){if(!isAbort(error)){setPageStatus('读取最近快照失败：'+error.message,'error');log('读取最近快照失败：'+error.message);}}finally{endAction(token);}}
async function clearInfoCache(){const p=params();const token=beginAction('clearInfoCacheBtn','正在清除该股票的信息快照缓存…');try{const js=await fetchJson(`/api/cache/clear?kind=info_snapshot&symbol=${encodeURIComponent(p.symbol)}`,{method:'POST'},'cache');if(js.ok===false)throw new Error(js.message||js.error||'缓存清除失败');state.analysis=null;state.pageData=null;state.global=null;$('items').innerHTML='<div class="empty">该股信息快照缓存已清除，请点击普通刷新或深度刷新重新抓取。</div>';$('summary').innerHTML='';setPageStatus('缓存已清除；下一次普通刷新会创建新的信息快照。','success');log('已清除该股信息快照缓存，可重新普通刷新或深度刷新');}catch(error){if(!isAbort(error)){setPageStatus('缓存清除失败：'+error.message,'error');log('缓存清除失败：'+error.message);}}finally{endAction(token);}}
function switchTab(tab){state.tab=tab;document.querySelectorAll('.tab').forEach(item=>item.classList.toggle('active',item.dataset.tab===tab));$('tabItems').style.display=tab==='items'?'block':'none';$('tabGlobal').style.display=tab==='global'?'block':'none';$('tabCalendar').style.display=tab==='calendar'?'block':'none';$('tabDedup').style.display=tab==='dedup'?'block':'none';$('tabDiagnostics').style.display=tab==='diagnostics'?'block':'none';$('tabFramework').style.display=tab==='framework'?'block':'none';if(tab==='global'&&!state.global)loadGlobal(false).catch(error=>{if(!isAbort(error))log('全球要闻读取失败：'+error.message);});if(tab==='calendar')renderCalendar();}
(async function init(){const query=new URLSearchParams(location.search);if(query.get('symbol'))$('symbol').value=query.get('symbol');if(query.get('name'))$('name').value=query.get('name');if(query.get('limit'))$('limit').value=query.get('limit');$('dimensionFilter').value='';$('category').value='';$('unknown').value='true';if(query.get('snapshot_id'))log('使用筛选快照编号='+query.get('snapshot_id'));const forced=query.get('force')==='true';await refreshAll(forced,false);const hasItemShape=Array.isArray(state.analysis?.items)||Array.isArray(state.analysis?.news?.items);const visibleItems=state.analysis?.items||state.analysis?.news?.items||[];const incompleteSnapshot=state.analysis?.snapshot_reused&&(!hasItemShape||state.analysis?.info_score==null||state.analysis?.cache_status?.status==='error');if(!forced&&query.get('snapshot_id')&&incompleteSnapshot){log('筛选页快照结构不完整，自动普通刷新补抓一次');await refreshAll(true,false);}else if(!forced&&!query.get('snapshot_id')&&!visibleItems.length){log('本地信息库暂无条目，首屏已完成；后台自动执行一次普通刷新');setTimeout(()=>refreshAll(true,false),80);}setInterval(()=>{if(!document.hidden&&state.tab==='global')loadGlobal(false).catch(()=>{});},60000);})();
</script>
</body></html>'''
