from __future__ import annotations


def build_info_ui() -> str:
    return r'''<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>信息面分析详情 V3.26</title>
<style>
  body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI","Microsoft YaHei",Arial,sans-serif;margin:0;background:#f5f7fb;color:#1f2937;}
  header{background:#0f172a;color:#fff;padding:14px 22px;display:flex;align-items:center;justify-content:space-between;gap:16px;position:sticky;top:0;z-index:10;box-shadow:0 6px 20px rgba(15,23,42,.18)}
  header h1{font-size:18px;margin:0;font-weight:800}.toplink{color:#bfdbfe;text-decoration:none;margin-left:12px;font-size:13px}
  main{padding:16px 20px;max-width:1420px;margin:0 auto;}
  .panel{background:#fff;border-radius:14px;box-shadow:0 4px 18px rgba(15,23,42,.08);padding:14px;margin-bottom:14px;border:1px solid #e5e7eb;}
  .controls{display:grid;grid-template-columns:repeat(10,minmax(92px,1fr));gap:10px;align-items:end;}
  label{font-size:12px;color:#64748b;display:block;margin-bottom:4px;} input,select,button{border:1px solid #d1d5db;border-radius:10px;padding:9px 10px;font-size:14px;background:#fff;box-sizing:border-box;width:100%;}
  button{cursor:pointer;background:#2563eb;color:#fff;border-color:#2563eb;font-weight:700;}button.secondary{background:#f8fafc;color:#334155;border-color:#cbd5e1;}button.green{background:#16a34a;border-color:#16a34a}button:disabled{opacity:.62;cursor:wait}
  .summary{display:grid;grid-template-columns:repeat(10,minmax(0,1fr));gap:10px;}.stat{background:#f8fafc;border:1px solid #e5e7eb;border-radius:12px;padding:10px;min-width:0}.stat .k{font-size:12px;color:#64748b}.stat .v{font-size:19px;font-weight:800;margin-top:4px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.stat .s{font-size:11px;color:#94a3b8;margin-top:3px;}
  .layout{display:grid;grid-template-columns:1fr 360px;gap:14px;align-items:start}.tabs{display:flex;flex-wrap:wrap;gap:8px;margin-bottom:10px}.tab{width:auto;background:#f8fafc;color:#334155;border:1px solid #cbd5e1;padding:8px 12px}.tab.active{background:#2563eb;color:#fff;border-color:#2563eb}
  .item{border:1px solid #e5e7eb;border-radius:12px;padding:12px;margin-bottom:10px;background:#fff;}.item h3{font-size:15px;margin:0 0 8px 0;line-height:1.45;}.item h3 a{color:#1e40af;text-decoration:none}.item h3 a:hover{text-decoration:underline}.meta{display:flex;flex-wrap:wrap;gap:6px 10px;font-size:12px;color:#64748b;margin-bottom:8px;}
  .badge{display:inline-flex;border-radius:999px;padding:2px 8px;background:#eef2ff;color:#3730a3;border:1px solid #c7d2fe;font-size:12px;align-items:center}.badge.neg{background:#fef2f2;color:#991b1b;border-color:#fecaca}.badge.pos{background:#f0fdf4;color:#166534;border-color:#bbf7d0}.badge.neu{background:#f8fafc;color:#475569;border-color:#e2e8f0}.badge.warn{background:#fffbeb;color:#92400e;border-color:#fde68a}.badge.macro{background:#eff6ff;color:#1d4ed8;border-color:#bfdbfe}.summary-text{font-size:13px;color:#475569;line-height:1.65;overflow-wrap:anywhere}.detail-text{margin-top:6px;font-size:12px;color:#475569}.detail-text summary{cursor:pointer;color:#1d4ed8;font-weight:700}.detail-text[open] summary{margin-bottom:6px}.evidence{font-size:12px;color:#334155;background:#f8fafc;border-radius:8px;padding:7px 9px;margin-top:8px;line-height:1.55;overflow-wrap:anywhere}
  .side h3{font-size:15px;margin:4px 0 10px}.barline{display:grid;grid-template-columns:90px 1fr 46px;gap:8px;align-items:center;border-bottom:1px dashed #e5e7eb;padding:7px 0;font-size:13px;}.bar{height:10px;background:#eef2f7;border-radius:999px;overflow:hidden;border:1px solid #e2e8f0}.bar i{display:block;height:100%;background:#60a5fa;width:0}.bar i.neg{background:#f87171}.bar i.pos{background:#4ade80}.bar i.warn{background:#facc15}
  .grid2{display:grid;grid-template-columns:1fr 1fr;gap:10px}.global-columns{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:12px;align-items:start}.global-card{background:#f8fafc;border:1px solid #e5e7eb;border-radius:12px;padding:10px;margin-bottom:8px}.global-card h4{font-size:14px;margin:0 0 6px}.global-list{max-height:680px;overflow:auto}.small{font-size:12px;color:#64748b}.log{white-space:pre-wrap;background:#0f172a;color:#e2e8f0;border-radius:10px;padding:10px;max-height:150px;overflow:auto;font-size:12px;}.pager{display:flex;gap:8px;align-items:center;justify-content:center;margin:14px 0}.pager button{width:auto;padding:8px 14px}.pager span{font-size:13px;color:#475569}.empty{padding:26px;text-align:center;color:#64748b;background:#f8fafc;border:1px dashed #cbd5e1;border-radius:12px}.warnbox{background:#fffbeb;border:1px solid #fde68a;color:#92400e;border-radius:12px;padding:10px;line-height:1.55;font-size:13px}.snapshot-box{background:#eff6ff;border:1px solid #bfdbfe;color:#1e40af;border-radius:12px;padding:10px;line-height:1.55;font-size:13px;margin-top:10px}.snapshot-box.loading{background:#fffbeb;border-color:#fde68a;color:#92400e}.snapshot-box.success{background:#f0fdf4;border-color:#bbf7d0;color:#166534}.snapshot-box.error{background:#fef2f2;border-color:#fecaca;color:#991b1b}.formula{background:#f8fafc;border:1px solid #e5e7eb;border-radius:10px;padding:9px;font-size:12px;line-height:1.6;color:#334155;}
  .event-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.event-card{border:1px solid #dbeafe;border-left:4px solid #60a5fa;border-radius:10px;padding:11px;background:#f8fbff;min-width:0}.event-card.high{border-left-color:#ef4444;background:#fff7f7}.event-card h4{margin:0 0 7px;font-size:14px;overflow-wrap:anywhere}.source-links{display:flex;flex-wrap:wrap;gap:8px;margin-top:7px}.source-links a{font-size:12px;color:#1d4ed8}.quality-full{background:#ecfdf5;color:#047857;border-color:#a7f3d0}.quality-excerpt{background:#eff6ff;color:#1d4ed8;border-color:#bfdbfe}.quality-title{background:#fffbeb;color:#92400e;border-color:#fde68a}.quality-rejected{background:#fef2f2;color:#991b1b;border-color:#fecaca}
  @media(max-width:1100px){.controls{grid-template-columns:repeat(2,1fr)}.layout{grid-template-columns:1fr}.summary{grid-template-columns:repeat(2,1fr)}.global-columns,.event-grid{grid-template-columns:1fr}}
</style>
</head>
<body>
<header><h1>信息面分析详情 V3.26 / 证据质量、快照复用、全球行业映射</h1><div><a class="toplink" href="/screener">返回筛选页</a><a class="toplink" href="/cache">缓存状态</a><a class="toplink" href="/ui">行情监控</a></div></header>
<main>
  <section class="panel">
    <div class="controls">
      <div><label>股票代码</label><input id="symbol" value="600519"></div>
      <div><label>股票名称</label><input id="name" value="贵州茅台"></div>
      <div><label>抓取/聚合上限</label><input id="limit" type="number" value="180" min="30" max="500"></div>
      <div><label>分页大小</label><input id="pageSize" type="number" value="30" min="5" max="200"></div>
      <div><label>排序</label><select id="sort"><option value="desc">时间倒序</option><option value="asc">时间正序</option></select></div>
      <div><label>信息模块</label><select id="dimensionFilter"><option value="">全部模块</option><option>官方公告/公司披露</option><option>公司消息</option><option>行业消息/政策消息</option><option>宏观经济消息</option><option>市场资金面消息</option><option>国际消息/全球市场</option><option>社会舆情/社区讨论</option></select></div>
      <div><label>事件类别</label><input id="category" placeholder="如 财报业绩"></div>
      <div><label>包含未知日期</label><select id="unknown"><option value="true">包含</option><option value="false">不包含</option></select></div>
      <div><button id="latestSnapshotBtn" class="secondary info-action" onclick="loadLatestSnapshot()">读取最近快照</button></div>
      <div><button id="refreshInfoBtn" class="green info-action" onclick="refreshAll(true,false)">普通刷新</button></div>
      <div><button id="deepRefreshInfoBtn" class="secondary info-action" onclick="refreshAll(false,true)">深度刷新</button></div>
      <div><button id="clearInfoCacheBtn" class="secondary info-action" onclick="clearInfoCache()">清除缓存</button></div>
    </div>
    <div id="snapshotBox" class="snapshot-box">当前使用筛选页快照时，详情页会优先读取 snapshot_id；只有强制抓取或深度刷新才重新抓取。</div>
    <div id="cacheStateBox" class="snapshot-box">缓存状态：等待加载。空数据时会显示 source_logs 和可执行动作，不再空白。</div>
    <div class="small" style="margin-top:8px">说明：搜索引擎关键词页彻底禁用；公司/公告信息需主动刷新或缓存过期才刷新。合法的空快照会保留来源诊断，不会在每次打开时重复联网。全球/国内/商品/政策要闻使用短缓存，只有与公司主营、业务标签、产业链暴露相关时才进入信息面映射分。</div>
  </section>

  <section class="panel summary" id="summary"></section>

  <div class="layout">
    <section>
      <div class="panel">
        <div class="tabs">
          <button class="tab active" data-tab="items" onclick="switchTab('items')">个股信息流</button>
          <button class="tab" data-tab="global" onclick="switchTab('global')">全球/行业映射</button>
          <button class="tab" data-tab="calendar" onclick="switchTab('calendar')">未来事件日历</button>
          <button class="tab" data-tab="dedup" onclick="switchTab('dedup')">去重与重复组</button>
          <button class="tab" data-tab="framework" onclick="switchTab('framework')">消息面框架</button>
        </div>
        <div id="tabItems">
          <div id="items"></div>
          <div class="pager"><button class="secondary" onclick="loadPage(state.page-1)">上一页</button><span id="pagerInfo">--</span><button class="secondary" onclick="loadPage(state.page+1)">下一页</button></div>
        </div>
        <div id="tabGlobal" style="display:none">
          <div class="grid2">
            <div class="global-card"><h4>全球/国内要闻模块分布</h4><div id="globalDims"></div></div>
            <div class="global-card"><h4>全球要闻情绪/风险结构</h4><div id="globalSent"></div></div>
          </div>
          <div class="global-columns">
            <div class="global-card"><h4>信息映射</h4><div id="industryMappedItems" class="global-list"></div></div>
            <div class="global-card"><h4>全球信息</h4><div id="globalItems" class="global-list"></div></div>
          </div>
        </div>
        <div id="tabCalendar" style="display:none"><div id="calendarBox"></div></div>
        <div id="tabDedup" style="display:none"><div id="dedupBox"></div></div>
        <div id="tabFramework" style="display:none"><div id="frameworkBox"></div></div>
      </div>
    </section>
    <aside class="side">
      <div class="panel"><h3>统计图</h3><div id="charts"></div></div>
      <div class="panel"><h3>评分模型</h3><div id="formula" class="formula">--</div></div>
      <div class="panel"><h3>信息源诊断</h3><div id="sources" class="small">--</div></div>
      <div class="panel"><h3>后台进度提示</h3><div class="log" id="log">页面日志会显示请求进度；命令窗也会同步打印 [信息面] 进度。</div></div>
    </aside>
  </div>
</main>
<script>
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let state={page:1,total_pages:1,analysis:null,pageData:null,global:null,tab:'items'};
let requestSeq=0;
let busyToken=0;
const requestControllers={analysis:null,page:null,global:null,snapshot:null,cache:null};
function log(msg){$('log').textContent=new Date().toLocaleTimeString()+' '+msg+'\n'+$('log').textContent;}
function params(){const u=new URLSearchParams(location.search);return {symbol:$('symbol').value.trim(),name:$('name').value.trim(),limit:Math.max(30,Math.min(500,Number($('limit').value)||180)),page_size:Math.max(5,Math.min(200,Number($('pageSize').value)||30)),sort:$('sort').value,include_unknown_date:$('unknown').value,snapshot_id:u.get('snapshot_id')||'',force:u.get('force')==='true'};}
function rememberSnapshot(p,sid){if(!sid)return;const u=new URL(location.href);u.searchParams.set('symbol',p.symbol);u.searchParams.set('name',p.name);u.searchParams.set('limit',String(p.limit));u.searchParams.set('snapshot_id',sid);u.searchParams.delete('force');history.replaceState(null,'',u);}
function stat(k,v,s=''){return `<div class="stat"><div class="k">${esc(k)}</div><div class="v">${esc(v)}</div>${s?`<div class="s">${esc(s)}</div>`:''}</div>`}
function cnInfoValue(v){const raw=String(v??'').trim();const map={macro:'宏观市场',global:'全球市场',company:'公司信息',company_event:'公司事件',industry:'行业信息',market:'市场资金',announcement:'公司公告',news:'新闻资讯',policy:'政策信息',research:'研究信息',general:'一般事件',commodity:'商品市场',earnings:'财报业绩',board_meeting:'董事会会议',research_report:'研究报告',holder_change:'股东持股变动',dividend:'分红派息',positive:'正向',negative:'负向',neutral:'中性',hit:'缓存命中',stale:'缓存过期',miss:'缓存缺失',error:'读取失败',ok:'正常',ready:'就绪',fresh:'最新数据',refreshed:'已刷新',skipped:'已跳过',disabled:'已禁用',unsupported:'暂不支持',timeout:'请求超时',no_data:'暂无数据',mapped:'已完成行业映射',background_refresh:'后台刷新中',true:'是',false:'否'};return map[raw]||raw}
function cnSourceName(v){const raw=String(v??'').trim();const map={global_news_cache:'全球要闻缓存',global_industry_mapper:'全球行业映射器',info_light:'信息面轻量缓存',info_snapshot:'信息面快照'};return map[raw]||raw||'未知来源'}
function bars(rows,nameKey='name',countKey='count',cls=''){const max=Math.max(1,...(rows||[]).map(x=>Number(x[countKey]||0)));return (rows||[]).map(x=>`<div class="barline"><span>${esc(cnInfoValue(x[nameKey]||x.category||x.source||'--'))}</span><div class="bar"><i class="${cls}" style="width:${Math.max(2,Number(x[countKey]||0)/max*100)}%"></i></div><b>${esc(x[countKey]||0)}</b></div>`).join('')||'<div class="small">暂无统计</div>'}
function sentCls(x){x=String(x||'');return x.includes('正')?'pos':x.includes('负')?'neg':'neu'}
function setPageStatus(message,kind=''){const box=$('cacheStateBox');box.className='snapshot-box'+(kind?' '+kind:'');box.textContent=message;}
function beginAction(buttonId,message){const token=++busyToken;document.querySelectorAll('.info-action').forEach(btn=>{if(!btn.dataset.originalText)btn.dataset.originalText=btn.textContent;btn.disabled=true;btn.textContent=btn.id===buttonId?'处理中…':btn.dataset.originalText;});setPageStatus(message,'loading');return token;}
function endAction(token){if(token!==busyToken)return;document.querySelectorAll('.info-action').forEach(btn=>{btn.disabled=false;btn.textContent=btn.dataset.originalText||btn.textContent;});}
function isAbort(error){return error?.name==='AbortError'}
async function fetchJson(url,options={},channel=''){if(channel&&requestControllers[channel])requestControllers[channel].abort();const controller=new AbortController();if(channel)requestControllers[channel]=controller;try{const response=await fetch(url,{cache:'no-store',...options,signal:controller.signal});if(!response.ok)throw new Error(`请求失败（HTTP ${response.status}）`);return await response.json();}finally{if(channel&&requestControllers[channel]===controller)requestControllers[channel]=null;}}
function renderSummary(){const a=state.analysis||{};const n=a.news||{};const cur=a.current_information_summary||{};const dq=a.data_quality||n.data_quality||{};const cal=a.future_event_calendar||{};const visible=(a.items||n.items||[]).length;const raw=visible||n.count||0;const unknown=cur.unknown_date_count??(a.items||n.items||[]).filter(x=>!(x.publish_time||x.published_at_norm||x.published_at||x.date)).length;$('summary').innerHTML=[stat('当前信息分',a.info_score??'--','仅近期已披露证据'),stat('近期计分',cur.current_scoring_count??0,'事件级去重'),stat('正文已核验',dq.verified_full_text_count??0,'全量分析口径'),stat('仅标题',dq.title_only_count??0,'已降低权重'),stat('合并转载',dq.merged_duplicate_count??0,'不重复计分'),stat('未来事件',cal.count??0,`确认 ${cal.confirmed_count??0} / 推算 ${cal.rule_inferred_count??0}`),stat('最新证据',cur.latest_published_at||'--','发布时间'),stat('全球映射分',a.policy?.policy_score??'--',`相关 ${a.global_news_used?.related_count??0}`),stat('未知日期',unknown,'只供查阅'),stat('分析/展示',`${n.count??raw} / ${visible}`,'列表有展示上限')].join('');$('formula').innerHTML=`<b>当前计分范围：</b><br>${esc(cur.score_scope||'仅近期、可核验、事件级去重信息参与当前评分；历史信息和未来结果只供观察。')}<br><br><b>统计口径：</b><br>摘要卡统计本轮全量去重结果，下面列表受展示上限约束，因此“正文已核验”可能多于当前页可见正文。<br><br><b>正文质量：</b><br>完整正文权重最高，结构化摘要次之，仅标题降低权重，网页壳拒绝进入正文评分。<br><br><b>未来事件：</b><br>${esc(cal.scoring_rule||'未来事件只提高观察频率，不直接加减分。')}<br><br><b>信息分公式：</b><br>${esc(a.score_model?.formula||'公司/事件 + 来源可信度 + 财务 + 全球/行业映射 - 传闻风险')}<br><br><b>摘要：</b><br>${esc(a.summary||a.diagnostics?.summary||'--')}`;const cs=a.cache_status||{};const usingSnapshot=!!(a.used_snapshot||a.snapshot_reused||(['hit','stale'].includes(String(cs.status||''))&&String(cs.source||'').includes('info_')));const snapshotLabel=a.mode==='snapshot_miss'?'快照不存在，未自动重抓':usingSnapshot?'使用筛选/最近快照':'使用手动刷新结果';$('snapshotBox').innerHTML=`${snapshotLabel}；快照编号=${esc(a.snapshot_id||'--')}；快照时间=${esc(a.updated_at||a.created_at||'--')}；近期计分=${esc(cur.current_scoring_count??0)}；历史排除=${esc(cur.historical_excluded_count??0)}；需要深挖时再点深度刷新。`;$('cacheStateBox').className='snapshot-box success';$('cacheStateBox').innerHTML=`缓存状态=${esc(cnInfoValue(cs.status||'--'))}；缓存年龄=${esc(cs.age_seconds??'--')}秒；有效期=${esc(cs.ttl_seconds??'--')}秒；数据源=${esc(cs.source||'--')}；${cs.stale?'当前展示过期缓存，可手动刷新。':'缓存可复用。'}`;renderCharts();renderSources();renderFramework();renderGlobal();renderCalendar();}
function renderCharts(){const n=(state.analysis||{}).news||{};const st=(state.pageData||{}).stats||{};$('charts').innerHTML=`<div class="small">消息面模块</div>${bars(n.dimension_counts||[])}<div class="small" style="margin-top:10px">事件类别</div>${bars(n.category_counts||st.by_category||[])}<div class="small" style="margin-top:10px">来源占比</div>${bars(n.source_counts||st.by_source||[])}`;}
function renderSources(){const a=state.analysis||{};const n=a.news||{};const status=a.source_logs||n.sources_status||[];$('sources').innerHTML=status.length?status.map(s=>`<div>【${esc(cnSourceName(s.source||s.source_name))}】${esc(s.count??0)}条：${esc(cnInfoValue(s.status||'--'))}${s.elapsed_ms!=null?' · '+esc(s.elapsed_ms)+'毫秒':''}${s.skipped_reason?' · '+esc(cnInfoValue(s.skipped_reason)):''}</div>`).join(''):'暂无诊断；如果个股信息为空，这里会显示最近抓取日志和错误原因。';}
function cnFrameworkKey(v){const raw=String(v??'');const map={dimensions:'信息维度',source_tiers:'信息源分层',official:'官方来源',media:'证券媒体',community:'社区舆情',scoring:'评分规则',dedup:'事件去重',freshness:'时效规则',blocked_sources:'禁用来源',search_engines:'搜索引擎'};return map[raw]||cnInfoValue(raw)}
function formatFrameworkValue(value){if(Array.isArray(value))return value.map(v=>formatFrameworkValue(v)).join('、');if(value&&typeof value==='object')return Object.entries(value).map(([k,v])=>`${esc(cnFrameworkKey(k))}：${formatFrameworkValue(v)}`).join('；');return esc(cnInfoValue(value))}
function renderFramework(){const a=state.analysis||{};const fw=a.message_framework||{};const sp=a.source_policy||{};let html='<div class="warnbox">消息面按宏观经济、行业、公司、市场资金面、国际消息、舆情分层。官方公告优先；社区只作舆情；搜索引擎结果页禁用。</div>';html+='<h3>消息面分析框架</h3>'+Object.entries(fw).map(([k,v])=>`<div class="item"><b>${esc(cnFrameworkKey(k))}</b><div class="small">${formatFrameworkValue(v)}</div></div>`).join('');html+='<h3>信息源分层</h3>'+Object.entries(sp).map(([k,v])=>`<div class="item"><b>${esc(cnFrameworkKey(k))}</b><div class="small">${formatFrameworkValue(v)}</div></div>`).join('');$('frameworkBox').innerHTML=html;}
function cnTime(x){return x?.publish_time||x?.published_at_norm||x?.published_at||x?.date||x?.created_at||'--'}
function cnCrawlTime(x){return x?.crawl_time||x?.fetched_at||x?.created_at||state.analysis?.created_at||'--'}
function cnDirection(v){return ({positive:'正向',negative:'负向',neutral:'中性'}[String(v||'neutral')]||cnInfoValue(v||'neutral'))}
function cnIncluded(x){return (x.included_in_score??x.score_included)?'纳入个股评分':'仅作市场背景'}
function mappedCard(x){return `<div class="global-card"><h4>${esc(x.title||'--')}</h4><div class="small">行业映射证据；来源：${esc(x.source||'--')}；发布时间：${esc(cnTime(x))}；抓取时间：${esc(cnCrawlTime(x))}</div><div class="small">行业：${esc((x.mapped_industries||[]).join('、')||'--')}；概念：${esc((x.mapped_concepts||[]).join('、')||'--')}；相关个股：${esc((x.mapped_symbols||[]).join('、')||'--')}</div><div class="small">事件：${esc(cnInfoValue(x.category||x.event_type||'general'))}；影响方向：${esc(cnDirection(x.impact_direction))}；相关性：${esc(x.relevance_score??'--')}；${esc(cnIncluded(x))}</div><div class="summary-text">影响原因：${esc(x.impact_reason||'--')}</div></div>`}
function renderLongText(value,maxLength=360){const text=String(value||'').trim();if(!text)return '';if(text.length<=maxLength)return `<div class="summary-text">${esc(text)}</div>`;return `<div class="summary-text">${esc(text.slice(0,maxLength))}…</div><details class="detail-text"><summary>展开完整摘要</summary><div class="summary-text">${esc(text)}</div></details>`}
function qualityMeta(x){const raw=String(x.content_quality_status||'title_only');const map={full_text:['正文已核验','quality-full'],structured_excerpt:['结构化摘要','quality-excerpt'],title_only:['仅标题证据','quality-title'],boilerplate_rejected:['网页壳已拒绝','quality-rejected']};return map[raw]||[cnInfoValue(raw),'quality-title']}
function renderItem(x){const sent=x.sentiment_label||((Number(x.sentiment_score||50)>=58)?'正面':(Number(x.sentiment_score||50)<=45?'负面':'中性'));const url=String(x.url||x.source_ref||'').trim();const attachment=String(x.attachment_url||'').trim();const title=esc(x.title||'--');const titleHtml=url&&url!=='#'?`<a href="${esc(url)}" target="_blank" rel="noreferrer">${title}</a>`:`<span>${title}</span>`;const evidence=(x.evidence||[]).map(esc).join('；');const quality=qualityMeta(x);const merged=Number(x.duplicate_count||1);const links=`<div class="source-links">${url&&url!=='#'?`<a href="${esc(url)}" target="_blank" rel="noreferrer">打开信息页面</a>`:'<span class="small">未提供原文链接</span>'}${attachment?`<a href="${esc(attachment)}" target="_blank" rel="noreferrer">打开公告PDF</a>`:''}</div>`;return `<article class="item"><h3>${titleHtml}</h3><div class="meta"><span>发布：${esc(cnTime(x))} / 事件：${esc(x.event_time||'--')} / 抓取：${esc(cnCrawlTime(x))}</span><span>来源：${esc(cnSourceName(x.source))}</span><span class="badge ${quality[1]}">${esc(quality[0])}</span><span class="badge macro">${esc(cnInfoValue(x.message_dimension||'公司信息'))}</span><span class="badge ${sentCls(sent)}">${esc(cnInfoValue(sent))}</span><span class="badge neu">${esc(cnInfoValue(x.category||'其他'))}</span><span class="badge warn">可信 ${esc(x.credibility_score??'--')} / 影响 ${esc(x.impact_score??'--')} / 传闻风险 ${esc(x.fake_risk_score??'--')}</span>${merged>1?`<span class="badge neu">已合并 ${merged} 条转载</span>`:''}</div>${renderLongText(x.summary)}${!x.summary&&x.content_missing_reason?`<div class="warnbox">${esc(x.content_missing_reason)}</div>`:''}${links}${x.target_relation?`<div class="evidence"><b>当前标的关系：</b>${esc(x.target_relation)}；${esc(x.relation_note||'')}</div>`:''}${evidence?`<div class="evidence"><b>证据：</b>${evidence}</div>`:''}${merged>1?`<div class="small">重复来源：${esc((x.duplicate_sources||[]).join('、')||'--')}</div>`:''}<div class="small">事件类型：${esc(cnInfoValue(x.event_type||'general'))}；周期：${esc(cnInfoValue(x.period||'--'))}；去重键：${esc(x.event_key||x.duplicate_group||'--')}；${esc(x.dedup_reason||'')}</div></article>`}
function renderCalendar(){const cal=state.analysis?.future_event_calendar||{};const rows=cal.events||[];const intro=`<div class="warnbox"><b>未来事件不直接计分。</b> ${esc(cal.scoring_rule||'只用于提高观察频率。')}<br>${esc(cal.truth_rule||'规则推算日期需再次核对官方日历。')}</div>`;$('calendarBox').innerHTML=intro+(rows.length?`<div class="event-grid" style="margin-top:10px">${rows.map(x=>`<article class="event-card ${x.attention_level==='高'?'high':''}"><h4>${esc(x.scheduled_at||'--')} · ${esc(x.title||x.event_type_cn||'未来事项')}</h4><div class="meta"><span class="badge ${x.confirmation_status==='公开来源已确认'?'quality-full':'quality-title'}">${esc(x.confirmation_status||'待核验')}</span><span class="badge ${x.attention_level==='高'?'neg':'neu'}">关注级别 ${esc(x.attention_level||'低')}</span><span>${esc(x.days_until??'--')} 天后</span></div><div class="small">影响窗口：${esc(x.impact_window||'--')}；方向：${esc(x.impact_direction||'结果待确认')}</div><div class="summary-text">${esc(x.monitoring_action||'加入观察清单')}</div>${x.source_ref?`<div class="source-links"><a href="${esc(x.source_ref)}" target="_blank" rel="noreferrer">核对公开来源</a></div>`:`<div class="small">${esc(x.confirmation_note||'无公开链接，必须再次核对官方日历')}</div>`}</article>`).join('')}</div>`:'<div class="empty" style="margin-top:10px">未来观察范围内暂无带明确日期的公开事项；系统不会因此伪造会议或财报日期。</div>')}
function renderItems(){const d=state.pageData||{};const original=d.data||[];let data=original;const dim=$('dimensionFilter').value;if(dim)data=data.filter(x=>(x.message_dimension||'')===dim);const rawItems=state.analysis?.items||state.analysis?.news?.items||[];const rawTotal=rawItems.length||d.total||original.length;const unknown=rawItems.filter(x=>!(x.publish_time||x.published_at_norm||x.published_at||x.date)).length;const mappedList=(state.analysis?.industry_mapped_items||[]).filter(x=>x.included_in_score||x.score_included);const mappedRelated=mappedList.length;const snapTime=state.analysis?.created_at||'--';let empty=mappedRelated?`<div class="empty">暂无个股新闻；以下展示 ${mappedRelated} 条行业/题材映射证据作为背景，不冒充个股新闻。快照时间：${esc(snapTime)}</div>`+mappedList.slice(0,12).map(mappedCard).join(''):`<div class="empty">暂无信息：当前没有个股条目；抓取日志和错误原因仍保留在下方，可读取最近快照、普通刷新或深度刷新。快照时间：${esc(snapTime)}</div>`;if(!data.length&&original.length)empty='<div class="empty">当前过滤条件导致 0 条。<button class="secondary" onclick="clearInfoFilters()">清空过滤条件</button></div>';$('items').innerHTML=data.length?data.map(renderItem).join(''):empty;$('pagerInfo').textContent=`第 ${state.page} / ${state.total_pages||1} 页；总数 ${d.total??0}；原始 ${rawTotal}；过滤后 ${data.length}；行业映射 ${mappedRelated}；未知日期 ${unknown}；模块=${$('dimensionFilter').value||'全部'}；事件=${$('category').value||'全部'}；包含未知日期=${cnInfoValue($('unknown').value)}`;}
function renderDedup(){const st=(state.pageData||{}).stats||{};const duplicates=st.duplicate_groups||[];$('dedupBox').innerHTML=`<div class="warnbox">重复组用于检查“同一事件多源转载是否重复计分”。系统按 event_key/duplicate_group 合并，只保留最高可信版本进入主评分。</div>${duplicates.length?duplicates.map(x=>`<div class="item"><b>${esc(x.title||'--')}</b><div class="small">重复 ${esc(x.c)} 条；去重键=${esc(x.duplicate_group||'')}</div></div>`).join(''):'<div class="empty">暂无重复组，或当前库已按事件合并。</div>'}`;}
function renderGlobal(){const g=state.global||{};const items=g.items||state.analysis?.global_items||[];const mapped=state.analysis?.industry_mapped_items||[];$('globalDims').innerHTML=`<div class="small">国内 ${g.domestic_count||0} / 全球 ${g.global_count||items.length||0} / 商品 ${g.commodity_count||0}；更新时间 ${esc(g.updated_at||state.analysis?.created_at||'--')}</div>`+bars(g.dimension_counts||g.category_counts||[]);$('globalSent').innerHTML=bars(g.market_category_counts||g.category_counts||[])+'<div class="small" style="margin-top:8px">情绪结构</div>'+bars([{name:'正向',count:g.positive_count||0},{name:'负向',count:g.negative_count||0},{name:'中性',count:g.neutral_count||0}]);$('industryMappedItems').innerHTML=mapped.length?mapped.slice(0,80).map(mappedCard).join(''):'<div class="empty">暂无全球/行业映射证据：可能是暂无全球新闻、与当前个股相关性不足，或公司画像缺失。不相关全球新闻不会计入个股分。</div>';$('globalItems').innerHTML=items.length?items.slice(0,180).map(renderItem).join(''):'<div class="empty">暂无全球要闻；请查看信息源诊断或执行普通/深度刷新。</div>';}
async function loadPage(page=1){const p=params();page=Math.max(1,page);$('pagerInfo').textContent='正在加载分页…';let url=`/api/info/items/${encodeURIComponent(p.symbol)}?page=${page}&page_size=${p.page_size}&sort=${p.sort}&include_unknown_date=${p.include_unknown_date}`;if($('category').value.trim())url+='&category='+encodeURIComponent($('category').value.trim());const js=await fetchJson(url,{},'page');if(js.ok===false)throw new Error(js.message||js.error||'信息分页读取失败');state.pageData=js.data||{};state.total_pages=state.pageData.total_pages||1;if(page>state.total_pages&&state.total_pages>0)return loadPage(1);state.page=page;renderItems();renderCharts();renderDedup();return state.pageData;}
function clearInfoFilters(){$('dimensionFilter').value='';$('category').value='';$('unknown').value='true';state.page=1;loadPage(1).catch(error=>{if(!isAbort(error)){log('过滤刷新失败：'+error.message);$('pagerInfo').textContent='分页读取失败，请重试';}})}
async function loadGlobal(force=false){const p=params();if(force||!state.global)log('读取全球/国内/商品要闻');const js=await fetchJson(`/api/news/global?limit=${Math.min(200,p.limit)}&force=${force}`,{},'global');if(js.ok===false)throw new Error(js.message||js.error||'全球要闻读取失败');state.global=js.data||{};renderGlobal();return state.global;}
async function refreshAll(force=false,deep=false){const seq=++requestSeq;const p=params();const buttonId=deep?'deepRefreshInfoBtn':'refreshInfoBtn';const token=beginAction(buttonId,`${deep?'深度刷新':force?'普通刷新':'读取快照/缓存'}中，请稍候…`);const refreshSnapshot=force||deep;if(refreshSnapshot)state.global=null;log((deep?'深度刷新':force?'普通刷新':'读取快照/缓存')+`：${p.name||p.symbol}，上限 ${p.limit} 条`);const sid=refreshSnapshot?'':p.snapshot_id;const url=`/api/info/analyze/${encodeURIComponent(p.symbol)}?name=${encodeURIComponent(p.name)}&limit=${p.limit}&force=${force}&deep_refresh=${deep}&snapshot_id=${encodeURIComponent(sid)}`;try{const js=await fetchJson(url,{},'analysis');if(seq!==requestSeq)return;if(!js.ok)throw new Error(js.message||js.error||'信息分析失败');state.analysis=js.data||{};rememberSnapshot(p,state.analysis.snapshot_id||js.snapshot_id);renderSummary();const results=await Promise.allSettled([loadPage(1),loadGlobal(force||deep)]);if(seq!==requestSeq)return;if(results[0].status==='rejected'&&!isAbort(results[0].reason)){const fallbackItems=state.analysis.items||state.analysis.news?.items||[];state.pageData={data:fallbackItems,total:fallbackItems.length,total_pages:1,stats:state.analysis.stats||{}};state.page=1;state.total_pages=1;renderItems();renderCharts();renderDedup();log('分页接口暂不可用，已展示分析快照内的数据');}if(results[1].status==='rejected'&&!isAbort(results[1].reason))log('全球要闻暂未更新：'+results[1].reason.message);renderSummary();log(`分析完成：信息面分=${state.analysis.info_score??'--'}，新闻=${state.analysis.news?.count??0}条，政策线索=${state.analysis.policy?.policy_clue_count??0}，${state.analysis.snapshot_reused?'复用快照':'已重新抓取/刷新'}`);}catch(error){if(!isAbort(error)&&seq===requestSeq){setPageStatus('信息分析失败：'+error.message,'error');log('信息分析失败：'+error.message);}}finally{endAction(token);}}
async function loadLatestSnapshot(){const p=params();const token=beginAction('latestSnapshotBtn','正在读取最近信息快照…');try{const js=await fetchJson(`/api/cache/info/latest/${encodeURIComponent(p.symbol)}`,{},'snapshot');if(js.ok&&js.data){state.analysis=js.data;rememberSnapshot(p,js.snapshot_id||state.analysis.snapshot_id);const fallbackItems=state.analysis.items||state.analysis.news?.items||[];state.pageData={data:fallbackItems,total:fallbackItems.length,total_pages:1,stats:state.analysis.stats||{}};state.page=1;state.total_pages=1;renderSummary();renderItems();renderCharts();renderDedup();const results=await Promise.allSettled([loadPage(1),loadGlobal(false)]);if(results[0].status==='rejected'&&!isAbort(results[0].reason))log('分页接口暂不可用，继续展示快照内的数据');if(results[1].status==='rejected'&&!isAbort(results[1].reason))log('全球要闻暂未更新：'+results[1].reason.message);renderSummary();log('已读取最近信息快照 '+(js.snapshot_id||state.analysis.snapshot_id||''));}else{log('暂无最近快照，自动执行普通刷新');await refreshAll(true,false);}}catch(error){if(!isAbort(error)){setPageStatus('读取最近快照失败：'+error.message,'error');log('读取最近快照失败：'+error.message);}}finally{endAction(token);}}
async function clearInfoCache(){const p=params();const token=beginAction('clearInfoCacheBtn','正在清除该股票的信息快照缓存…');try{const js=await fetchJson(`/api/cache/clear?kind=info_snapshot&symbol=${encodeURIComponent(p.symbol)}`,{method:'POST'},'cache');if(js.ok===false)throw new Error(js.message||js.error||'缓存清除失败');state.analysis=null;state.pageData=null;state.global=null;$('items').innerHTML='<div class="empty">该股信息快照缓存已清除，请点击普通刷新或深度刷新重新抓取。</div>';$('summary').innerHTML='';setPageStatus('缓存已清除；下一次普通刷新会创建新的信息快照。','success');log('已清除该股信息快照缓存，可重新普通刷新或深度刷新');}catch(error){if(!isAbort(error)){setPageStatus('缓存清除失败：'+error.message,'error');log('缓存清除失败：'+error.message);}}finally{endAction(token);}}
function switchTab(tab){state.tab=tab;document.querySelectorAll('.tab').forEach(item=>item.classList.toggle('active',item.dataset.tab===tab));$('tabItems').style.display=tab==='items'?'block':'none';$('tabGlobal').style.display=tab==='global'?'block':'none';$('tabCalendar').style.display=tab==='calendar'?'block':'none';$('tabDedup').style.display=tab==='dedup'?'block':'none';$('tabFramework').style.display=tab==='framework'?'block':'none';if(tab==='global'&&!state.global)loadGlobal(false).catch(error=>{if(!isAbort(error))log('全球要闻读取失败：'+error.message);});if(tab==='calendar')renderCalendar();}
(async function init(){const query=new URLSearchParams(location.search);if(query.get('symbol'))$('symbol').value=query.get('symbol');if(query.get('name'))$('name').value=query.get('name');if(query.get('limit'))$('limit').value=query.get('limit');$('dimensionFilter').value='';$('category').value='';$('unknown').value='true';if(query.get('snapshot_id'))log('使用筛选快照编号='+query.get('snapshot_id'));const forced=query.get('force')==='true';await refreshAll(forced,false);const hasItemShape=Array.isArray(state.analysis?.items)||Array.isArray(state.analysis?.news?.items);const visibleItems=state.analysis?.items||state.analysis?.news?.items||[];const incompleteSnapshot=state.analysis?.snapshot_reused&&(!hasItemShape||state.analysis?.info_score==null||state.analysis?.cache_status?.status==='error');if(!forced&&query.get('snapshot_id')&&incompleteSnapshot){log('筛选页快照结构不完整，自动普通刷新补抓一次');await refreshAll(true,false);}else if(!forced&&!query.get('snapshot_id')&&!visibleItems.length){log('本地信息库暂无条目，首屏已完成；后台自动执行一次普通刷新');setTimeout(()=>refreshAll(true,false),80);}setInterval(()=>{if(!document.hidden&&state.tab==='global')loadGlobal(false).catch(()=>{});},60000);})();
</script>
</body></html>'''
