from __future__ import annotations


def build_live_trading_ui() -> str:
    return r'''<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>真实自动交易 V3.24</title><!-- 真实自动交易 V3.23 兼容入口 -->
<style>
:root{--bg:#08111f;--panel:#101a2c;--panel2:#0c1626;--line:#263955;--text:#e7f0ff;--muted:#91a6c5;--blue:#3b82f6;--green:#22c55e;--red:#ef4444;--amber:#f59e0b}
*{box-sizing:border-box}html,body{margin:0;min-height:100%;background:var(--bg);color:var(--text);font-family:"Segoe UI","Microsoft YaHei",Arial,sans-serif}a{color:#bfdbfe;text-decoration:none}button,input,select,textarea{font:inherit}
header{height:58px;display:flex;align-items:center;gap:10px;padding:0 16px;background:#0b1424;border-bottom:1px solid var(--line);position:sticky;top:0;z-index:10}.dot{width:10px;height:10px;border-radius:50%;background:var(--green);box-shadow:0 0 12px var(--green)}.brand{font-weight:900;font-size:20px}.grow{flex:1}.pill{padding:5px 10px;border:1px solid #315077;border-radius:999px;background:#13233b;color:#cfe1ff;font-size:12px;font-weight:800}.pill.warn{border-color:#854d0e;background:#2a1e08;color:#fde68a}.pill.bad{border-color:#7f1d1d;background:#2a1116;color:#fecaca}
main{display:grid;grid-template-columns:320px minmax(680px,1fr);gap:12px;padding:12px;min-height:calc(100vh - 58px)}.side,.workspace{display:grid;gap:12px;align-content:start}.panel{background:var(--panel);border:1px solid var(--line);border-radius:8px;overflow:hidden}.head{min-height:44px;padding:8px 12px;display:flex;align-items:center;justify-content:space-between;gap:8px;background:#121e33;border-bottom:1px solid var(--line);font-weight:900}.body{padding:12px}.grid2{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.row{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.field{display:grid;gap:5px;margin-bottom:9px}.field label{font-size:12px;color:#9db4d4;font-weight:800}.field small{color:var(--muted);line-height:1.45}
input,select,textarea{width:100%;padding:8px 9px;color:var(--text);background:#0d1728;border:1px solid #2f4364;border-radius:7px;outline:none}textarea{min-height:70px;resize:vertical;line-height:1.45}.btn,button{border:0;border-radius:7px;padding:8px 11px;background:#253755;color:var(--text);font-weight:800;cursor:pointer}.btn:hover,button:hover{filter:brightness(1.12)}button:disabled{opacity:.55;cursor:wait}.primary{background:var(--blue)!important}.green{background:#15803d!important}.red{background:#991b1b!important}.notice{padding:10px;border:1px solid #2f4364;border-radius:7px;background:#0d1728;color:#c9d9ef;font-size:13px;line-height:1.55;overflow-wrap:anywhere}.notice.danger{border-color:#7f1d1d;color:#fecaca}.muted{color:var(--muted)}.ok{color:#86efac}.bad{color:#fca5a5}.warn{color:#fcd34d}
.metrics{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:8px}.metric{padding:10px;background:var(--panel2);border:1px solid #2b3e5e;border-radius:7px;min-width:0}.metric span{display:block;color:var(--muted);font-size:12px}.metric b{display:block;margin-top:6px;font-size:19px;overflow-wrap:anywhere}
.tabs{display:flex;gap:6px;overflow:auto;padding:8px 10px;background:#0d1728;border-bottom:1px solid var(--line)}.tab{white-space:nowrap;background:#1d2d48}.tab.active{background:var(--blue)}.tab-pane{display:none;padding:10px}.tab-pane.active{display:block}.table-wrap{max-width:100%;overflow:auto;border:1px solid #2b3e5e;border-radius:7px;max-height:460px}table{width:100%;border-collapse:collapse;table-layout:fixed;min-width:900px;font-size:12px}th,td{padding:8px;border-bottom:1px solid #243653;text-align:left;vertical-align:top;overflow-wrap:anywhere}th{position:sticky;top:0;background:#14223a;color:#9fd4ff;z-index:1}.actions{display:flex;gap:6px;flex-wrap:wrap}.actions button{padding:5px 8px;font-size:12px}.strategy-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:6px;max-height:210px;overflow:auto}.strategy{display:grid;grid-template-columns:auto 1fr;gap:7px;padding:7px;border:1px solid #2f4364;border-radius:7px;background:#0d1728}.strategy input{width:auto;margin-top:3px}.strategy b,.strategy small{display:block}.strategy small{color:var(--muted);margin-top:2px}.output{max-height:190px;overflow:auto;white-space:pre-wrap;word-break:break-word;font-size:12px;background:#090f1b;border:1px solid #2b3e5e;border-radius:7px;padding:8px}.footer-note{font-size:12px;color:#8fa6c8;text-align:center;padding:4px 12px 12px}
@media(max-width:1180px){main{grid-template-columns:1fr}.metrics{grid-template-columns:repeat(3,minmax(0,1fr))}}@media(max-width:720px){header{position:static;height:auto;min-height:58px;flex-wrap:wrap;padding:10px}main{padding:8px}.grid2,.strategy-grid{grid-template-columns:1fr}.metrics{grid-template-columns:repeat(2,minmax(0,1fr))}}
</style>
</head>
<body>
<header><span class="dot"></span><div class="brand">真实自动交易 V3.24</div><span id="brokerPill" class="pill warn">券商状态读取中</span><span class="pill bad">默认禁用 · 人工确认</span><div class="grow"></div><a href="/auto-trading">总控台</a><a href="/realtime-paper">实时模拟</a><a href="/trading-records">交易记录</a><a href="/data-center">数据中心</a></header>
<main>
<aside class="side">
  <section class="panel"><div class="head"><span>多股票实盘观察池</span><button onclick="loadWorkbenchConfig(this)">读取总控台</button></div><div class="body">
    <div class="field"><label>交易标的与订单</label><textarea id="symbols">300750, 600438, 510300</textarea><small>支持逗号、空格或换行分隔；每只股票独立预检查和风控。</small></div>
    <div class="grid2"><div class="field"><label>方向</label><select id="side"><option value="buy">买入</option><option value="sell">卖出</option></select></div><div class="field"><label>数量（股）</label><input id="quantity" type="number" min="100" step="100" value="100"></div><div class="field"><label>委托类型</label><select id="orderType"><option value="limit">限价</option><option value="best_effort">最优五档</option><option value="target_percent">目标仓位</option><option value="target_value">目标金额</option></select></div><div class="field"><label>限价（0=预检参考价）</label><input id="limitPrice" type="number" min="0" step="0.01" value="0"></div></div>
    <div class="row"><button class="primary" onclick="batchPreview(this)">批量预检查</button><button class="green" onclick="submitConfirmation(this)">提交确认队列</button><button class="red" onclick="setKillSwitch(this)">实盘 Kill</button></div>
    <div class="table-wrap" style="margin-top:9px;max-height:210px"><table><thead><tr><th>代码</th><th>策略数</th><th>方向</th><th>数量</th><th>参考限价</th><th>状态</th></tr></thead><tbody id="watchRows"><tr><td colspan="6">等待加载观察池</td></tr></tbody></table></div>
  </div></section>
  <section class="panel"><div class="head"><span>实盘策略目录</span><span id="strategyCount" class="muted">0 项</span></div><div class="body">
    <div class="field"><label>策略族</label><select id="strategyFamily"><option value="short">短线</option><option value="swing" selected>波段</option><option value="position">长线持仓</option><option value="dca">定投</option><option value="core_satellite">核心-卫星</option><option value="event_driven">事件驱动</option><option value="avoid">风险回避</option></select></div>
    <div class="row" style="margin-bottom:8px"><button onclick="loadLiveIntradayPreset()">载入实盘分时策略</button><button onclick="selectAllAvailableStrategies()">使用全部可用策略</button></div>
    <div id="strategyList" class="strategy-grid"><span class="muted">正在读取策略目录...</span></div>
  </div></section>
  <section class="panel"><div class="head"><span>统一风控</span><span class="muted">下单前强制检查</span></div><div class="body grid2">
    <div class="field"><label>止损 %</label><input id="stopLossPct" type="number" value="8"></div><div class="field"><label>止盈 %</label><input id="takeProfitPct" type="number" value="18"></div><div class="field"><label>单票仓位上限 %</label><input id="maxSinglePositionPct" type="number" value="20"></div><div class="field"><label>最大回撤 %</label><input id="maxDrawdownPct" type="number" value="18"></div>
  </div></section>
  <section class="panel"><div class="head"><span>券商安全状态</span><button onclick="connectBroker(this)">连接检查</button></div><div class="body"><div id="safety" class="notice">正在读取...</div><pre id="output" class="output">Ready.</pre></div></section>
</aside>
<section class="workspace">
  <div id="metrics" class="metrics"></div>
  <section class="panel"><div class="head"><span>账户与持仓</span><div class="row"><a href="/trading-records">打开统一记录</a><button onclick="loadAll(this)">刷新</button><button onclick="runReconciliation(this)">执行对账</button></div></div>
    <div class="tabs"><button class="tab active" data-tab="account" onclick="openTab('account')">实盘账户</button><button class="tab" data-tab="orders" onclick="openTab('orders')">委托与确认</button><button class="tab" data-tab="fills" onclick="openTab('fills')">成交流水</button><button class="tab" data-tab="ledger" onclick="openTab('ledger')">统一账本</button><button class="tab" data-tab="reconcile" onclick="openTab('reconcile')">对账结果</button></div>
    <div id="pane-account" class="tab-pane active"><div id="accountNotice" class="notice"></div><h3>当前持仓</h3><div class="table-wrap"><table><thead><tr><th>代码</th><th>名称</th><th>持仓</th><th>可用</th><th>平均成本</th><th>最新价</th><th>市值</th><th>浮盈亏</th><th>盈亏%</th><th>数据源</th></tr></thead><tbody id="positionRows"></tbody></table></div></div>
    <div id="pane-orders" class="tab-pane"><div class="notice" style="margin-bottom:8px"><b>实盘委托与成交</b>：真实委托/成交、待人工确认、预检查/拦截分阶段保存；预检查不会计入这里的真实成交统计。</div><div class="table-wrap"><table><thead><tr><th>阶段</th><th>时间</th><th>代码</th><th>方向</th><th>价格</th><th>数量</th><th>状态</th><th>原因</th><th>操作</th></tr></thead><tbody id="orderRows"></tbody></table></div></div>
    <div id="pane-fills" class="tab-pane"><div class="table-wrap"><table><thead><tr><th>成交时间</th><th>代码</th><th>方向</th><th>成交价</th><th>股数</th><th>成交额</th><th>费用</th><th>税费</th><th>滑点</th><th>成交来源</th></tr></thead><tbody id="fillRows"></tbody></table></div></div>
    <div id="pane-ledger" class="tab-pane"><div class="notice">买入、卖出、佣金、税费、滑点和已实现盈亏分别记账；成交不会再被合并成一条不可追溯记录。</div><div class="table-wrap" style="margin-top:8px"><table><thead><tr><th>发生时间</th><th>代码</th><th>账务类型</th><th>方向</th><th>股数</th><th>价格</th><th>金额</th><th>订单/成交</th><th>来源</th></tr></thead><tbody id="ledgerRows"></tbody></table></div></div>
    <div id="pane-reconcile" class="tab-pane"><div id="reconcileSummary" class="notice">尚未执行对账。</div><pre id="reconcileOutput" class="output" style="max-height:430px">等待对账...</pre></div>
  </section>
  <section class="panel"><div class="head"><span>批量预检查结果</span><span class="muted">预检查不会直接下单</span></div><div class="body"><div class="table-wrap"><table><thead><tr><th>代码</th><th>方向</th><th>数量</th><th>状态</th><th>风控与数据原因</th></tr></thead><tbody id="previewRows"><tr><td colspan="5">等待预检查</td></tr></tbody></table></div></div></section>
</section>
</main>
<div class="footer-note">研究辅助，不构成投资建议；真实交易需用户自行确认合规与风险。</div>
<script>
const $=id=>document.getElementById(id);let config={},catalog=[],selectedStrategies=new Set(),lastPreview=[];
const LIVE_INTRADAY_STRATEGIES=['score_driven','vwap_strength','volume_breakout','fund_flow_watch','fake_order_cancel_watch','orderbook_imbalance_watch','global_commodity_map','market_regime','risk_control'];
const LIVE_ORDER_PREVIEW_API='/api/live/orders/preview',LIVE_TRADES_API='/api/live/trades';
const cn={buy:'买入',sell:'卖出',needs_confirmation:'待人工确认',risk_blocked:'风控拦截',prechecked:'预检查通过',submitted:'已提交',accepted:'已受理',partially_filled:'部分成交',filled:'已成交',cancel_requested:'撤单申请中',cancelled:'已撤单',canceled:'已撤单',rejected:'已拒单',failed:'失败',commission:'佣金',tax:'税费',slippage:'滑点',realized_pnl:'已实现盈亏'};
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}function label(v){return cn[v]||v||'--'}function num(id,f=0){const n=Number($(id).value);return Number.isFinite(n)?n:f}function money(v){const n=Number(v);return Number.isFinite(n)?n.toLocaleString('zh-CN',{maximumFractionDigits:2}):'--'}function pct(v){const n=Number(v);return Number.isFinite(n)?n.toFixed(2)+'%':'--'}function cls(v){const n=Number(v);return n>0?'ok':n<0?'bad':''}function split(v){return [...new Set(String(v||'').split(/[\s,，;；、]+/).map(x=>x.trim()).filter(Boolean))]}function symbols(){return split($('symbols').value)}async function api(url,opt){const r=await fetch(url,opt);let d={};try{d=await r.json()}catch(e){d={ok:false,message:'接口返回不是 JSON'}}if(!r.ok&&d.ok!==false)d.ok=false;return d}function busy(btn,text,fn){if(!btn)return fn();const old=btn.textContent;btn.disabled=true;btn.textContent=text;return Promise.resolve(fn()).finally(()=>{btn.disabled=false;btn.textContent=old})}
function openTab(name){document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===name));document.querySelectorAll('.tab-pane').forEach(x=>x.classList.toggle('active',x.id==='pane-'+name))}
function strategyPayload(){return [...selectedStrategies]}function orderPayload(){return {symbols:symbols(),symbol:symbols()[0]||'',side:$('side').value,quantity:num('quantity',100),order_type:$('orderType').value,limit_price:num('limitPrice',0)||null,strategy_family:$('strategyFamily').value,selected_strategies:strategyPayload(),strategy_combo:strategyPayload(),risk_controls:{stop_loss_pct:num('stopLossPct',8),take_profit_pct:num('takeProfitPct',18),max_single_position_pct:num('maxSinglePositionPct',20),max_drawdown_pct:num('maxDrawdownPct',18)},source_page:'live-trading'} }
function renderStrategies(){const selected=selectedStrategies;$('strategyCount').textContent=selected.size+' 项';$('strategyList').innerHTML=catalog.map(x=>{const key=String(x.key||'');return `<label class="strategy"><input type="checkbox" data-key="${esc(key)}" ${selected.has(key)?'checked':''} onchange="toggleStrategy(this)"><span><b>${esc(x.name||key)}</b><small>${esc(x.beginner_note||x.description||x.category||'统一策略因子')}</small></span></label>`}).join('')||'<span class="muted">策略目录暂不可用；系统不会用虚假策略替代。</span>';renderWatchRows()}function toggleStrategy(el){el.checked?selectedStrategies.add(el.dataset.key):selectedStrategies.delete(el.dataset.key);renderStrategies()}
function loadLiveIntradayPreset(){selectedStrategies=new Set(LIVE_INTRADAY_STRATEGIES);$('strategyFamily').value='short';renderStrategies()}
function selectAllAvailableStrategies(){selectedStrategies=new Set(catalog.map(x=>String(x.key||'')).filter(Boolean));renderStrategies()}
function renderWatchRows(preview=[]){const previewMap={};(preview.length?preview:lastPreview).forEach(x=>{const r=x.preview||x.result||x.response||x;previewMap[String(x.symbol||r.symbol||'')]=r});$('watchRows').innerHTML=symbols().map(sym=>{const r=previewMap[sym]||{},ok=!!(r.ok||r.approved||['prechecked','needs_confirmation'].includes(r.status)),state=r.status||r.message||(Object.keys(r).length?(ok?'预检查通过/待确认':'预检查未通过'):'待预检查');return `<tr><td>${esc(sym)}</td><td>${selectedStrategies.size}</td><td>${esc(label($('side').value))}</td><td>${esc($('quantity').value)}</td><td>${esc($('limitPrice').value||'0')}</td><td class="${Object.keys(r).length?(ok?'ok':'bad'):''}">${esc(label(state))}</td></tr>`}).join('')||'<tr><td colspan="6">请先输入监控标的</td></tr>'}
async function loadWorkbenchConfig(btn){return busy(btn,'读取中...',async()=>{const [c,l]=await Promise.all([api('/api/auto-trading/config'),api('/api/strategy/library')]);config=c.data||{};catalog=config.strategy_catalog||l.data||[];const combo=config.strategy_combo||l.default_keys||[];selectedStrategies=new Set(combo.map(String));if((config.symbols||[]).length)$('symbols').value=config.symbols.join(', ');const risk=config.risk_controls||{};for(const [id,key] of [['stopLossPct','stop_loss_pct'],['takeProfitPct','take_profit_pct'],['maxSinglePositionPct','max_single_position_pct'],['maxDrawdownPct','max_drawdown_pct']])if(risk[key]!=null)$(id).value=risk[key];renderStrategies()})}
function renderPreview(rows){lastPreview=rows||[];$('previewRows').innerHTML=lastPreview.map(x=>{const r=x.preview||x.result||x.response||x;const ok=!!(r.ok||r.approved||r.status==='needs_confirmation'||r.status==='prechecked');return `<tr><td>${esc(x.symbol||r.symbol)}</td><td>${label(r.side||$('side').value)}</td><td>${esc(r.quantity||$('quantity').value)}</td><td class="${ok?'ok':'bad'}">${esc(label(r.status||r.message||(ok?'通过':'未通过')))}</td><td>${esc(r.status_reason||r.reason||r.risk?.reason||r.message||'--')}</td></tr>`}).join('')||'<tr><td colspan="5">暂无结果</td></tr>';renderWatchRows(lastPreview)}
async function batchPreview(btn){return busy(btn,'预检查中...',async()=>{const js=await api('/api/live/orders/preview-batch',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(orderPayload())});renderPreview(js.data||[]);$('output').textContent=JSON.stringify(js,null,2);openTab('orders');return js})}
async function submitConfirmation(btn){return busy(btn,'提交中...',async()=>{const js=await api('/api/live/orders/place-batch',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...orderPayload(),confirmed:false})});renderPreview(js.data||[]);$('output').textContent=JSON.stringify(js,null,2);await loadOrders();openTab('orders')})}
async function approve(id,btn){return busy(btn,'确认中...',async()=>{const js=await api('/api/live/orders/confirm',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({confirm_id:id})});$('output').textContent=JSON.stringify(js,null,2);await loadAll()})}
async function connectBroker(btn){return busy(btn,'检查中...',async()=>{const js=await api('/api/live-broker/connect',{method:'POST'});$('output').textContent=JSON.stringify(js,null,2);await loadAll()})}async function setKillSwitch(btn){if(!confirm('确认启用全局实盘 Kill Switch？启用后所有真实下单都会被阻断。'))return;return busy(btn,'启用中...',async()=>{const js=await api('/api/live/kill-switch',{method:'POST',headers:{'content-type':'application/json'},body:'{"enabled":true}'});$('output').textContent=JSON.stringify(js,null,2);await loadAll()})}
function renderStatus(js){const b=js.broker||{},s=js.safety||{};$('brokerPill').textContent=`${b.broker||js.config?.broker_type||'disabled'} · ${label(b.status||js.status||'disabled')}`;$('brokerPill').className='pill '+(b.connected?'':'warn');$('safety').innerHTML=`<b>连接：</b>${b.connected?'已连接':'未连接'}　<b>实盘开关：</b>${s.LIVE_TRADING_ENABLED?'开启':'关闭'}<br><b>人工确认：</b>${s.ORDER_CONFIRM_REQUIRED?'必须':'未启用'}　<b>Kill Switch：</b>${s.LIVE_KILL_SWITCH?'已启用':'未启用'}<br><span class="muted">未安装 SDK、未配置环境变量、未授权账户时会显示 disabled/unsupported，绝不会伪造连接或成交。</span>`}
function renderAccount(a,p){const d=a.data||a.account||{},rows=p.data||[];const cash=d.available_cash??d.cash?.available_cash,eq=d.total_equity??d.equity,mv=d.position_market_value??d.market_value,up=d.unrealized_pnl,rp=d.realized_pnl,day=d.daily_pnl;const available=a.data_available!==false&&d.authorized!==false;$('accountNotice').className='notice '+(available?'':'danger');$('accountNotice').innerHTML=available?`账户 ${esc(d.account_id||'--')} · 数据源 ${esc(d.source||a.source?.status||'券商适配器')} · 更新时间 ${esc(d.fetched_at||'--')}`:`<b>未连接真实账户</b><br>${esc(a.missing_reason||d.missing_reason||(a.missing_reasons||[]).join('；')||'券商未连接、未授权或接口不支持')}`;$('metrics').innerHTML=[['可用资金',money(cash),''],['总权益',money(eq),''],['持仓市值',money(mv),''],['浮盈亏',money(up),cls(up)],['已实现盈亏',money(rp),cls(rp)],['当日盈亏',money(day),cls(day)]].map(x=>`<div class="metric"><span>${x[0]}</span><b class="${x[2]}">${x[1]}</b></div>`).join('');$('positionRows').innerHTML=rows.map(x=>{const q=Number(x.quantity||0),cost=Number(x.display_cost_price??x.avg_cost??x.cost_price),price=Number(x.market_price??x.last_price),mv=Number(x.market_value??q*price),pnl=Number(x.unrealized_pnl??q*(price-cost)),pp=Number(x.display_pnl_pct??x.unrealized_pnl_pct??(cost?(price-cost)/cost*100:0));return `<tr><td>${esc(x.symbol)}</td><td>${esc(x.name||'--')}</td><td>${esc(q)}</td><td>${esc(x.available_quantity??'--')}</td><td>${money(cost)}</td><td>${money(price)}</td><td>${money(mv)}</td><td class="${cls(pnl)}">${money(pnl)}</td><td class="${cls(pp)}">${pct(pp)}</td><td>${esc(x.source||'--')}</td></tr>`}).join('')||'<tr><td colspan="10">暂无真实持仓；券商未连接时不会用 0 冒充账户数据。</td></tr>'}
async function loadOrders(){const [o,q]=await Promise.all([api('/api/live/orders?scope=all&limit=500'),api('/api/live/confirm-queue')]);const rows=[];(q.data||[]).forEach(x=>rows.push({...x,stage:'人工确认',isConfirmation:true}));(o.data||[]).forEach(x=>rows.push({...x,stage:x.record_stage_cn||'委托'}));$('orderRows').innerHTML=rows.map(x=>{const id=x.confirm_id||x.id||'';const can=x.isConfirmation&&String(x.status||'pending')==='pending';return `<tr><td>${esc(x.stage)}</td><td>${esc(x.updated_at||x.created_at||'--')}</td><td>${esc(x.symbol||x.request?.symbol||'--')}</td><td>${esc(label(x.side||x.request?.side))}</td><td>${money(x.limit_price??x.price??x.request?.limit_price)}</td><td>${esc(x.quantity??x.request?.quantity??'--')}</td><td>${esc(label(x.status))}</td><td>${esc(x.status_reason||x.reason||x.message||'--')}</td><td class="actions">${can?`<button class="green" onclick="approve('${esc(id)}',this)">人工批准</button>`:'--'}</td></tr>`}).join('')||'<tr><td colspan="9">暂无委托或待确认订单。</td></tr>'}
function renderFills(js){$('fillRows').innerHTML=(js.data||[]).map(x=>`<tr><td>${esc(x.filled_at||x.created_at||'--')}</td><td>${esc(x.symbol)}</td><td>${esc(label(x.side))}</td><td>${money(x.price)}</td><td>${esc(x.quantity??'--')}</td><td>${money(x.amount??Number(x.price)*Number(x.quantity))}</td><td>${money(x.fee)}</td><td>${money(x.tax)}</td><td>${money(x.slippage)}</td><td>${esc(x.source||x.broker||'--')}</td></tr>`).join('')||'<tr><td colspan="10">暂无真实成交。</td></tr>'}
function renderLedger(js){$('ledgerRows').innerHTML=(js.data||[]).map(x=>`<tr><td>${esc(x.occurred_at||x.created_at||'--')}</td><td>${esc(x.symbol||'--')}</td><td>${esc(label(x.entry_type))}</td><td>${esc(label(x.side))}</td><td>${esc(x.quantity??'--')}</td><td>${money(x.price)}</td><td class="${cls(x.amount)}">${money(x.amount)}</td><td>${esc((x.order_id||'--')+' / '+(x.fill_id||'--'))}</td><td>${esc(x.source||'--')}</td></tr>`).join('')||'<tr><td colspan="9">暂无账本记录；只有真实成交回报才会写入。</td></tr>'}
async function runReconciliation(btn){return busy(btn,'对账中...',async()=>{const js=await api('/api/live/reconciliation/run',{method:'POST'});$('reconcileOutput').textContent=JSON.stringify(js,null,2);const d=js.data||js;$('reconcileSummary').innerHTML=js.ok?`对账已完成。券商订单差异 ${esc((d.missing_orders||d.order_differences||[]).length||0)} 项，成交差异 ${esc((d.missing_trades||d.trade_differences||[]).length||0)} 项。`:`<span class="bad">对账未完成：${esc(js.message||js.reason||'券商不可用')}</span>`;openTab('reconcile')})}
async function loadAll(btn){return busy(btn,'刷新中...',async()=>{const [s,a,p,f,l]=await Promise.all([api('/api/live-broker/status'),api('/api/live/account'),api('/api/live/positions'),api('/api/live/fills?limit=500'),api('/api/live/ledger?limit=1000')]);renderStatus(s);renderAccount(a,p);renderFills(f);renderLedger(l);await loadOrders()})}
loadWorkbenchConfig().then(()=>loadAll()).catch(e=>{$('output').textContent=String(e)});
</script>
</body></html>'''
