from __future__ import annotations


def build_live_trading_ui() -> str:
    return """<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><title>真实自动交易 V3.23</title>
<style>
body{margin:0;background:#0b1020;color:#dbeafe;font-family:Segoe UI,Microsoft YaHei,Arial,sans-serif}header{height:58px;display:flex;align-items:center;gap:10px;padding:0 18px;background:#101827;border-bottom:1px solid #283956}.dot{width:10px;height:10px;border-radius:50%;background:#22c55e}.brand{font-weight:900;font-size:20px;color:#bfdbfe}.pill{border:1px solid #374151;background:#172033;border-radius:999px;padding:5px 10px}.danger{color:#fecaca;border-color:#7f1d1d;background:#2a1116}.grow{flex:1}a,button{color:#fff}button{border:0;border-radius:10px;background:#2563eb;padding:9px 12px;font-weight:800;cursor:pointer}.red{background:#991b1b}.green{background:#16a34a}main{display:grid;grid-template-columns:360px 1fr 420px;gap:14px;padding:14px}.panel{background:#111827;border:1px solid #26364f;border-radius:14px;overflow:hidden}.h{padding:12px;background:#141f35;border-bottom:1px solid #26364f;font-weight:900}.b{padding:12px}input,select{width:100%;box-sizing:border-box;background:#1f2937;color:#e5e7eb;border:1px solid #374151;border-radius:9px;padding:9px;margin:5px 0 10px}pre{white-space:pre-wrap;word-break:break-word;background:#0d1428;border:1px solid #26364f;border-radius:12px;padding:12px;min-height:260px}.muted{color:#91a7c7}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.card{background:#172033;border:1px solid #293954;border-radius:10px;padding:10px;min-width:0}.card b{display:block;overflow-wrap:anywhere}
</style></head><body><header><span class="dot"></span><div class="brand">真实自动交易 V3.23</div><span class="pill danger">默认禁用 · 必须人工确认</span><div class="grow"></div><a href="/auto-trading">自动交易总控台</a><a href="/realtime-paper">实时模拟</a><a href="/trading-records">交易记录</a><a href="/ui">行情监控</a></header>
<main><section class="panel"><div class="h">订单预览</div><div class="b"><label>代码</label><input id="symbol" value="300750"><label>方向</label><select id="side"><option value="buy">买入</option><option value="sell">卖出</option></select><label>数量</label><input id="quantity" type="number" value="100"><label>限价</label><input id="limitPrice" type="number" value="0"><label>策略族</label><select id="family"><option value="swing">波段</option><option value="short_term">短线</option><option value="long_term">长线</option><option value="core_satellite">核心-卫星</option></select><button onclick="preview()">预检查</button> <button onclick="place()">提交</button> <button class="red" onclick="kill()">Kill Switch</button><p class="muted">未配置券商和开启环境变量前，真实下单会被拒绝并进入审计。</p></div></section>
<section class="panel"><div class="h">状态</div><div class="b"><div id="cards" class="grid"></div><pre id="out">Loading...</pre></div></section>
<section class="panel"><div class="h">确认队列 / 订单</div><div class="b"><button onclick="load()">刷新</button><pre id="queue">Loading...</pre></div></section></main>
<script>
const $=id=>document.getElementById(id);function esc(v){return String(v??'')}function payload(){return{symbol:$('symbol').value,side:$('side').value,quantity:Number($('quantity').value),limit_price:Number($('limitPrice').value)||null,strategy_family:$('family').value,source_page:'live-trading'}}async function api(url,opt){const r=await fetch(url,opt);return await r.json()}function renderStatus(js){const s=js.safety||{},b=js.broker||{};$('cards').innerHTML=[['券商状态',b.status||'--'],['真实交易',s.LIVE_TRADING_ENABLED?'开启':'关闭'],['人工确认',s.ORDER_CONFIRM_REQUIRED?'必须':'关闭'],['Kill',s.LIVE_KILL_SWITCH?'开启':'关闭']].map(x=>`<div class="card"><span class="muted">${x[0]}</span><b>${x[1]}</b></div>`).join('');$('out').textContent=JSON.stringify(js,null,2)}async function load(){renderStatus(await api('/api/live-broker/status'));$('queue').textContent=JSON.stringify({confirm:await api('/api/live/confirm-queue'),orders:await api('/api/live/orders'),records:await api('/api/trading-records?mode=live&limit=20')},null,2)}async function preview(){renderStatus(await api('/api/live/orders/preview',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload())}))}async function place(){renderStatus(await api('/api/live/orders/place',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload())}));await load()}async function kill(){renderStatus(await api('/api/live/kill-switch',{method:'POST'}));await load()}load()
</script></body></html>"""
